"""#137 REVERSAL-ECHO -- is SSV irreversibility dynamical or boundary-data?

Pre-registered on issue #137 (S1 audit + S2 battery + decision rules
posted before computing). Decides the issue's central fork:

  Branch A (coarse-graining): the SSV dynamics is conservative and
  T-symmetric; wake irreversibility is Boltzmann's missing information
  with the forgotten variables named. Branch B (fundamental): requires
  an explicit non-conservative element, with vortex reconnection as the
  candidate. DEATH for branch B if exact time reversal recovers the
  pre-event configuration.

S1 analytic audit (the prediction; derivation in the result note):
the master dynamics is generated by the real energy functional

    E[psi] = int [ 1/2|grad psi|^2 + U(rho) + (lam/2 rho0^2)|curl j|^2 ],
    U(rho) = b(rho ln rho - rho + 1)   (SSV-I eq. "pot", vacuum-zeroed),

so the flow is Hamiltonian (conserves E and the norm), and under
t -> -t, psi -> psi* every term maps to itself (j is T-odd, enters
squared). The saturation potential as written is a conservative
potential -- it carries no dissipation. S1 therefore PREDICTS:
item 1 = PASS/branch-A, and the item-2 echo must recover.

S2 battery (this script):
  A  conservativity numeric: energy/norm drift through the event,
     bare LogSE and chiral-on.
  B  2D annihilation exact echo: colliding v-av dipoles annihilate,
     wake radiates, conjugate at t_end ~ 2 t_annih, evolve back, compare.
     Refinement ladder N = 256/512/1024 with dt ~ dx^2: numerical
     losses (dealiasing projection -- the scheme's one non-unitary
     element -- and fp64 round-off amplified by the event) must shrink
     under refinement; genuine dissipation would not.
     NUMERICS LESSON (deviation from the pre-registered "dt halved with
     each refinement", recorded per rule 1): the split-step LogSE has a
     Weideman-Herbst-type splitting resonance -- modes whose kinetic
     phase per step k^2 dt/2 reaches pi/2 are parametrically amplified
     when the event puts spectral content there. At N=512, dt=0.025 the
     dealias cutoff sat exactly on the resonance (k_cut = 11.17 vs
     k_pi/2 = sqrt(pi/dt) = 11.21) and the run blew up at t ~ 30;
     dt = 0.0125 is clean (drift ~ 0). The ladder therefore pins the
     cutoff phase at k_cut^2 dt/2 = pi/8, i.e. dt scales with dx^2.
     Decision rules are unchanged.
  C  boundary-data sensitivity: perturb the reversed field by
     psi -> psi(1 + eps*eta) and watch recovery die -- the Price/
     boundary-data content of SSV-III sec. 8, quantified. Forward-
     perturbation control gives the Lyapunov baseline.
  D  3D genuine reconnection: a Hopf link of two vortex rings
     (periodic-clean; linked rings CANNOT separate without
     reconnecting, and the first reconnection merges the core tubes
     2 -> 1 -- the discriminator), N = 64^3 / 96^3, reversal point set
     adaptively after the merger; the exact echo must restore the
     pre-reconnection topology. (The pre-registered 'oblique colliding
     rings' geometry was built first and passed through without
     reconnecting -- see hopf_link_3d for the recorded deviation.)

Numerics follow #129/#138 conventions (hbar = m0 = 1, b = 1, rho0 =
rhobar = 1, Strang split-step, 2/3-rule dealiased, fp64, PERIODIC box =
closed system, no absorbers). Imaginary-time relaxation preconditioner
per the #119 H7a lesson (removes imprint sound; winding protected).

Run:  python instruments/paper_iii/reversal_echo.py [--quick]
Writes papers/SSV-III/results/reversal_echo_receipt[_quick].json and
papers/SSV-III/figures/reversal_echo_battery.png.
"""

from __future__ import annotations

import json
import math
import sys
import time as _time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
RESULTS = ROOT / "papers" / "SSV-III" / "results"
FIGURES = ROOT / "papers" / "SSV-III" / "figures"

B0 = 1.0                      # log coupling: c_s = sqrt(B0) = 1
XI = 1.0 / math.sqrt(2 * B0)  # healing length in these units
# Log regularization floor at vortex-core zeros. The LogSE term is
# regular there (|psi|^2 ln|psi|^2 -> 0), but a raw floor of ~1e-300
# lets grid points adjacent to a core zero acquire phase rotations of
# b*ln(rho)*dt/2 ~ -690*dt -- spectral pollution that destabilizes the
# split-step (the same amplification that destabilized the #119 H8c
# fine-grid relaxer). Flooring at 1e-6 caps the rotation at a fraction
# of a radian while leaving every point with rho > 1e-6 untouched; the
# substep stays exactly unitary and exactly T-invertible, so the echo
# protocol is unaffected.
RHO_FLOOR = 1e-6


# ----------------------------------------------------------------------
# medium (2D and 3D scalar LogSE, optional chiral advection)
# ----------------------------------------------------------------------

class Medium:
    """Split-step LogSE on a periodic grid (2D or 3D), dealiased.

    Optional chiral-shear advection (2D only): the #138-derived EOM term
    dpsi/dt -= G.grad psi, G = (lam/rho0^2)(dy w, -dx w), w = curl j,
    integrated as an RK2 substep."""

    def __init__(self, shape, dx, lam=0.0):
        self.shape, self.dx, self.lam = tuple(shape), dx, lam
        self.ndim = len(shape)
        ks = [2 * np.pi * np.fft.fftfreq(n, dx) for n in shape]
        KK = np.meshgrid(*ks, indexing="ij")
        self.K = KK
        self.k2 = sum(k**2 for k in KK)
        mask = np.ones(self.shape, bool)
        for k, kv in zip(KK, ks):
            mask &= np.abs(k) <= (2 / 3) * np.abs(kv).max()
        self.dealias = mask.astype(float)

    def _d(self, f, axis):
        return np.fft.ifftn(1j * self.K[axis] * self.dealias
                            * np.fft.fftn(f))

    def grad(self, f):
        return [self._d(f, a) for a in range(self.ndim)]

    def current(self, psi):
        return [(np.conj(psi) * g).imag for g in self.grad(psi)]

    def curl_j_2d(self, psi):
        jx, jy = self.current(psi)
        return (self._d(jy, 0) - self._d(jx, 1)).real

    def energy(self, psi):
        """E = int 1/2|grad|^2 + U(rho) + (lam/2)|curl j|^2, vacuum-zeroed."""
        rho = np.abs(psi)**2
        e_kin = 0.5 * sum(float(np.sum(np.abs(g)**2)) for g in self.grad(psi))
        with np.errstate(divide="ignore", invalid="ignore"):
            u = B0 * (rho * np.where(rho > 0, np.log(np.maximum(rho, RHO_FLOOR)),
                                     0.0) - rho + 1.0)
        e_pot = float(np.sum(u))
        e_chi = 0.0
        if self.lam and self.ndim == 2:
            w = self.curl_j_2d(psi)
            e_chi = 0.5 * self.lam * float(np.sum(w**2))
        return (e_kin + e_pot + e_chi) * self.dx**self.ndim

    def norm(self, psi):
        return float(np.sum(np.abs(psi)**2)) * self.dx**self.ndim

    def _chiral_rhs(self, psi):
        w = self.curl_j_2d(psi)
        gx = self.lam * self._d(w, 1).real
        gy = -self.lam * self._d(w, 0).real
        g = self.grad(psi)
        return -(gx * g[0] + gy * g[1])

    def step(self, psi, dt):
        rho = np.abs(psi)**2
        psi = psi * np.exp(-1j * B0 * np.log(np.maximum(rho, RHO_FLOOR))
                           * (dt / 2))
        psi = np.fft.ifftn(np.fft.fftn(psi)
                           * (np.exp(-1j * self.k2 * (dt / 2))
                              * self.dealias))
        if self.lam and self.ndim == 2:
            f1 = self._chiral_rhs(psi)
            f2 = self._chiral_rhs(psi + 0.5 * dt * f1)
            psi = psi + dt * f2
        rho = np.abs(psi)**2
        return psi * np.exp(-1j * B0 * np.log(np.maximum(rho, RHO_FLOOR))
                            * (dt / 2))

    def relax(self, psi, n_iter, dtau):
        """Imaginary-time preconditioner (#119 H7a lesson): the LogSE
        vacuum at rho0 = 1 has exactly zero energy, so imprints relax
        with no renormalisation and protected winding."""
        kin = np.exp(-self.k2 * (dtau / 2)) * self.dealias
        for _ in range(n_iter):
            rho = np.abs(psi)**2
            psi = psi * np.exp(-B0 * np.log(np.maximum(rho, RHO_FLOOR))
                               * (dtau / 2))
            psi = np.fft.ifftn(np.fft.fftn(psi) * kin)
            rho = np.abs(psi)**2
            psi = psi * np.exp(-B0 * np.log(np.maximum(rho, RHO_FLOOR))
                               * (dtau / 2))
        return psi


# ----------------------------------------------------------------------
# defects
# ----------------------------------------------------------------------

def winding_map(psi):
    """Plaquette winding numbers of a 2D field (periodic)."""
    th = np.angle(psi)

    def dwrap(a):
        return (a + np.pi) % (2 * np.pi) - np.pi

    dx_ = dwrap(np.roll(th, -1, 0) - th)
    dy_ = dwrap(np.roll(th, -1, 1) - th)
    circ = dx_ + np.roll(dy_, -1, 0) - np.roll(dx_, -1, 1) - dy_
    return np.rint(circ / (2 * np.pi)).astype(int)


def defects_2d(psi, dx):
    """List of (x, y, charge) for plaquette windings of a 2D field."""
    w = winding_map(psi)
    ii, jj = np.nonzero(w)
    n0, n1 = psi.shape
    return [((i - n0 / 2 + 0.5) * dx, (j - n1 / 2 + 0.5) * dx, int(w[i, j]))
            for i, j in zip(ii, jj)]


def defects_match(d_ref, d_got, tol):
    """Same count, and every reference defect has a same-charge partner
    within tol (greedy nearest matching)."""
    if len(d_ref) != len(d_got):
        return False
    got = list(d_got)
    for x, y, q in d_ref:
        best, bi = None, None
        for i, (x2, y2, q2) in enumerate(got):
            if q2 != q:
                continue
            r = math.hypot(x - x2, y - y2)
            if best is None or r < best:
                best, bi = r, i
        if best is None or best > tol:
            return False
        got.pop(bi)
    return True


def fidelity(a, b):
    num = abs(np.vdot(a, b))**2
    den = float(np.sum(np.abs(a)**2)) * float(np.sum(np.abs(b)**2))
    return float(num / den)


# ----------------------------------------------------------------------
# initial states
# ----------------------------------------------------------------------

def colliding_dipoles_2d(n, dx, d, s):
    """Two tight vortex-antivortex dipoles at x = -/+ s, opposite
    orientation, on a head-on collision course (annihilation completes
    on impact). GEOMETRY NOTE, recorded per rule 1: the pre-registration
    wrote 'vortex-antivortex pair'; a single isolated pair is a
    traveling solitary object that does not annihilate in free flight
    (and a pair tight enough to annihilate spontaneously is destroyed
    by the imaginary-time preconditioner, since v-av winding is not
    topologically protected). The event class and all decision rules
    are unchanged: defect count -> 0 with a radiated sound burst.
    Quadrupole-symmetric configuration also keeps the periodic seam
    clean (#119 H7a lesson)."""
    x = (np.arange(n) - n / 2) * dx
    X, Y = np.meshgrid(x, x, indexing="ij")

    def pair(cx, sign):
        Zp = (X - cx) + 1j * (Y - d / 2)
        Zm = (X - cx) + 1j * (Y + d / 2)
        ph = sign * (np.angle(Zp) - np.angle(Zm))
        return (np.tanh(np.abs(Zp) / XI) * np.tanh(np.abs(Zm) / XI)
                * np.exp(1j * ph))

    return (pair(-s, +1) * pair(+s, -1)).astype(complex)


def hopf_link_3d(n, dx, R, z1=-2.0):
    """Two LINKED vortex rings (Hopf link): ring 1 with axis z, centre
    (0,0,z1); ring 2 with axis x, centre (0, R-1, z1), threading ring 1.
    Each ring is a 2D vortex-image pair in its own (s, axial) half-plane
    (closed rings: periodic-clean, no net flux through any face).

    GEOMETRY NOTE (recorded per rule 1): the pre-registration wrote
    'two oblique colliding vortex rings'. That geometry was built and
    validated first -- and the rings passed through each other without
    reconnecting (probe run: final probe-plane punctures = the initial
    rings, intact, at the post-crossing positions; the echo recovered
    them at F = 0.9999). A topology-FORCED geometry replaces it: linked
    rings cannot separate without reconnecting, and the first
    reconnection merges them 2 -> 1 (clean discriminator). Event class
    and decision rules unchanged."""
    x = (np.arange(n) - n / 2) * dx
    X, Y, Z = np.meshgrid(x, x, x, indexing="ij")
    cy = R - 1.0

    # ring 1: axis z, centre (0, 0, z1)
    s1 = np.sqrt(X**2 + Y**2)
    chi1 = np.arctan2(Z - z1, s1 - R) - np.arctan2(Z - z1, s1 + R)
    amp1 = np.tanh(np.sqrt((s1 - R)**2 + (Z - z1)**2) / XI)
    # ring 2: axis x, centre (0, cy, z1)
    s2 = np.sqrt((Y - cy)**2 + (Z - z1)**2)
    chi2 = np.arctan2(X, s2 - R) - np.arctan2(X, s2 + R)
    amp2 = np.tanh(np.sqrt((s2 - R)**2 + X**2) / XI)
    return (amp1 * amp2 * np.exp(1j * (chi1 + chi2))).astype(complex)


def low_density_components(psi, thr=0.25, min_size=5):
    """Connected low-density components above a minimum voxel count
    (diagnostic only -- a 2-ring -> 2-ring exchange reconnection does
    not change this count; the binding 3D observable is the probe-plane
    winding pattern below)."""
    from scipy.ndimage import label
    lab, nlab = label(np.abs(psi)**2 < thr)
    if nlab == 0:
        return 0
    sizes = np.bincount(lab.ravel())
    return int(np.sum(sizes[1:] >= min_size))


def plane_punctures(psi3d, dx, axis, index):
    """Probe-plane winding pattern (the pre-registered probe-loop
    observable): plaquette windings of the field restricted to one
    coordinate plane. A vortex line puncturing the plane appears as a
    +-1 winding at the puncture point; ring reconnection rearranges the
    puncture pattern even when the number of rings is unchanged."""
    sl = [slice(None)] * 3
    sl[axis] = index
    return defects_2d(psi3d[tuple(sl)], dx)


# ----------------------------------------------------------------------
# echo machinery
# ----------------------------------------------------------------------

class BlowUp(RuntimeError):
    pass


def evolve(med, psi, n_steps, dt, record_every=0, recorder=None):
    out = []
    for i in range(n_steps):
        psi = med.step(psi, dt)
        if (i + 1) % 200 == 0 and not np.isfinite(psi.flat[0]):
            raise BlowUp(f"non-finite field at step {i + 1}")
        if record_every and (i + 1) % record_every == 0 and recorder:
            out.append(recorder(psi, (i + 1) * dt))
    return psi, out


def echo_run(med, psi0, n_steps, dt, eps=0.0, seed=137):
    """Forward n_steps, conjugate (T), optional perturbation
    psi -> psi(1+eps*eta), forward n_steps, conjugate; return the echo
    field (directly comparable to psi0)."""
    psi, _ = evolve(med, psi0, n_steps, dt)
    psi = np.conj(psi)
    if eps:
        rng = np.random.default_rng(seed)
        eta = (rng.standard_normal(psi.shape)
               + 1j * rng.standard_normal(psi.shape)) / math.sqrt(2)
        psi = psi * (1.0 + eps * eta)
    psi, _ = evolve(med, psi, n_steps, dt)
    return np.conj(psi)


def find_annihilation(med, psi0, dt, t_max, check_every=20):
    """First time the defect count drops to zero (and stays there for
    one check window). Returns (t_annih or None, count timeline)."""
    psi = psi0.copy()
    n_steps = int(round(t_max / dt))
    timeline = []
    t_hit = None
    for i in range(n_steps):
        psi = med.step(psi, dt)
        if (i + 1) % check_every == 0:
            t = (i + 1) * dt
            nd = len(defects_2d(psi, med.dx))
            timeline.append((t, nd))
            if nd == 0 and t_hit is None:
                t_hit = t
            if nd > 0 and t_hit is not None and t - t_hit < 2 * check_every * dt:
                t_hit = None        # transient zero, keep looking
            if t_hit is not None and t > t_hit + 10:
                break
    return t_hit, timeline


# ----------------------------------------------------------------------
# the battery
# ----------------------------------------------------------------------

def run_2d_echo(n, L, dt, d, relax_iter=50, lam=0.0, eps_list=(),
                t_end=None, tag=""):
    """One 2D annihilation echo at resolution n. If t_end is given
    (from a coarser ladder run -- the annihilation time is physics, not
    resolution), the annihilation search is skipped and annihilation is
    instead verified on the tracked forward leg."""
    dx = L / n
    med = Medium((n, n), dx, lam=lam)
    psi0 = med.relax(colliding_dipoles_2d(n, dx, d, s=L / 8.0),
                     relax_iter, 0.02)
    d0 = defects_2d(psi0, dx)
    e0, norm0 = med.energy(psi0), med.norm(psi0)

    t_annih = None
    if t_end is None:
        t_annih, timeline = find_annihilation(med, psi0, dt, t_max=150.0)
        if t_annih is None:
            return {"tag": tag, "annihilated": False,
                    "timeline": timeline}
        t_end = 2.0 * t_annih
    n_steps = int(round(t_end / dt))

    t0 = _time.time()
    # forward leg with energy/norm tracking (run A)
    rec = lambda p, t: (t, med.energy(p), med.norm(p))
    psi_f, track = evolve(med, psi0, n_steps, dt,
                          record_every=max(1, n_steps // 40), recorder=rec)
    es = np.array([r[1] for r in track])
    ns = np.array([r[2] for r in track])
    annihilated = len(defects_2d(psi_f, dx)) == 0

    # exact echo: reuse the forward field
    psi_b, _ = evolve(med, np.conj(psi_f), n_steps, dt)
    psi_echo = np.conj(psi_b)
    F = fidelity(psi0, psi_echo)
    d_echo = defects_2d(psi_echo, dx)
    recovered = defects_match(d0, d_echo, tol=2 * XI)

    out = {
        "tag": tag, "n": n, "dx": dx, "dt": dt, "lam": lam,
        "annihilated": bool(annihilated),
        "t_annih": t_annih, "t_end": t_end,
        "n_defects_initial": len(d0),
        "energy_initial": e0,
        "energy_drift_rel": float(np.max(np.abs(es - e0)) / abs(e0)),
        "norm_drift_rel": float(np.max(np.abs(ns - norm0)) / norm0),
        "fidelity_exact": F,
        "defects_recovered_exact": bool(recovered),
        "n_defects_echo": len(d_echo),
        "walltime_s": _time.time() - t0,
    }
    # run C: perturbed echoes + forward Lyapunov control
    rng_eta = None
    for eps in eps_list:
        rng = np.random.default_rng(137)
        eta = (rng.standard_normal(psi0.shape)
               + 1j * rng.standard_normal(psi0.shape)) / math.sqrt(2)
        psi_b, _ = evolve(med, np.conj(psi_f) * (1.0 + eps * eta),
                          n_steps, dt)
        psi_p = np.conj(psi_b)
        out[f"fidelity_eps{eps:.0e}"] = fidelity(psi0, psi_p)
        out[f"defects_recovered_eps{eps:.0e}"] = bool(
            defects_match(d0, defects_2d(psi_p, dx), tol=2 * XI))
        psi_c, _ = evolve(med, psi0 * (1.0 + eps * eta), n_steps, dt)
        out[f"forward_overlap_eps{eps:.0e}"] = fidelity(psi_f, psi_c)
    print(f"  [{tag}] N={n} t_end={t_end:.1f} F_exact={F:.6f} "
          f"recovered={recovered} annihilated={annihilated} "
          f"Edrift={out['energy_drift_rel']:.2e} "
          f"({out['walltime_s']:.0f}s)", flush=True)
    return out


def run_3d_echo(n, L, dt, R, t_max, t_after=6.0, tag=""):
    """Hopf-link reconnection echo. Forward evolution is monitored; the
    reversal point is set adaptively at (first persistent topology
    change of the core tubes: merger or fragment production) + t_after,
    so the echo runs back through a completed reconnection without
    accumulating long-tangle dealiasing losses. Probe planes y = 0 and
    z = 0 (ring 2 lies in the x = 0 plane, which is therefore unusable:
    a core lying IN the probe plane makes plaquette windings
    degenerate)."""
    dx = L / n
    med = Medium((n, n, n), dx)
    psi0 = med.relax(hopf_link_3d(n, dx, R), 120, 0.02)
    e0, norm0 = med.energy(psi0), med.norm(psi0)
    i_mid = n // 2
    probe_axes = (1, 2)
    punct0 = {ax: plane_punctures(psi0, dx, ax, i_mid)
              for ax in probe_axes}
    comp0 = low_density_components(psi0)

    t0 = _time.time()
    comps = []
    psi = psi0.copy()
    check = max(1, int(round(1.0 / dt)))     # monitor every ~1 time unit
    t_rec, n_steps_done = None, 0
    n_max = int(round(t_max / dt))
    merged_run, frag_run = 0, 0
    while n_steps_done < n_max:
        psi = med.step(psi, dt)
        n_steps_done += 1
        if n_steps_done % check == 0:
            t = n_steps_done * dt
            c = low_density_components(psi)
            comps.append((round(t, 2), c))
            # topology-change trigger: a persistent merger (2 -> 1) or
            # persistent fragment production (>= 4 tubes: post-
            # reconnection products) -- a linked pair cannot do either
            # without reconnecting; single-frame counts are threshold
            # noise at marginal resolution and are ignored
            merged_run = merged_run + 1 if c == 1 else 0
            frag_run = frag_run + 1 if c >= 4 else 0
            if t_rec is None and (merged_run >= 2 or frag_run >= 3):
                t_rec = t - 2.0          # first of the persistent run
            if t_rec is not None and t >= t_rec + t_after:
                break
    e_end = med.energy(psi)
    punct_end = {ax: plane_punctures(psi, dx, ax, i_mid)
                 for ax in probe_axes}
    reconnected = t_rec is not None

    # exact echo over the same number of steps
    psi_b, _ = evolve(med, np.conj(psi), n_steps_done, dt)
    psi_echo = np.conj(psi_b)
    F = fidelity(psi0, psi_echo)
    punct_echo = {ax: plane_punctures(psi_echo, dx, ax, i_mid)
                  for ax in probe_axes}
    # recovery binds on the probe-plane winding patterns (the
    # pre-registered observable); the component count is recorded as a
    # diagnostic only -- single-frame counts flicker by +-1 from
    # threshold noise even on the unperturbed forward run
    recovered = all(defects_match(punct0[ax], punct_echo[ax],
                                  tol=2 * XI) for ax in probe_axes)
    comp_echo = low_density_components(psi_echo)
    out = {
        "tag": tag, "n": n, "dx": dx, "dt": dt,
        "t_reconnect": t_rec, "t_end": n_steps_done * dt,
        "punctures_initial": {str(a): p for a, p in punct0.items()},
        "punctures_t_end": {str(a): p for a, p in punct_end.items()},
        "punctures_echo": {str(a): p for a, p in punct_echo.items()},
        "components_initial": comp0, "components_timeline": comps,
        "components_echo": comp_echo,
        "reconnection_observed": bool(reconnected),
        "topology_recovered": bool(recovered),
        "fidelity_exact": F,
        "energy_drift_rel": float(abs(e_end - e0) / abs(e0)),
        "norm_drift_rel": float(abs(med.norm(psi) - norm0) / norm0),
        "walltime_s": _time.time() - t0,
    }
    print(f"  [{tag}] N={n}^3 t_rec={t_rec} F_exact={F:.6f} "
          f"recovered={recovered} Edrift={out['energy_drift_rel']:.2e} "
          f"({out['walltime_s']:.0f}s)", flush=True)
    return out


def battery(quick=False):
    out = {"config": {"quick": quick, "b0": B0, "xi": XI,
                      "geometry": "two colliding v-av dipoles, d = 4 xi, "
                                  "s = L/8 (see colliding_dipoles_2d note)"}}
    L = 96.0
    d = 4.0 * XI                       # dipole separation (survives relax)
    # pre-registered eps in {1e-12 .. 1e-3}; the range is EXTENDED
    # upward after the first run showed near-perfect recovery at 1e-3
    # (no chaotic amplification at the single-event scale -- recorded
    # per rule 1 as a failed pre-stated expectation); the added values
    # locate where recovery actually dies
    eps_list = (1e-12, 1e-9, 1e-6, 1e-3, 3e-2, 1e-1, 3e-1)

    # ---- B: refinement ladder (with A tracking and C at mid res) ----
    print("B: 2D annihilation echo ladder ...", flush=True)
    # dt ~ dx^2: cutoff phase pinned at k_cut^2 dt/2 = pi/8 (see the
    # splitting-resonance numerics lesson in the module docstring)
    if quick:
        ladder = [(256, 0.025), (512, 0.00625)]
        mid = 256
    else:
        ladder = [(256, 0.025), (512, 0.00625), (1024, 0.0015625)]
        mid = 512
    runs = []
    t_end_shared = None
    for n, dt in ladder:
        r = run_2d_echo(n, L, dt, d,
                        eps_list=eps_list if n == mid else (),
                        t_end=t_end_shared, tag=f"ladder N={n}")
        if t_end_shared is None and r.get("annihilated"):
            t_end_shared = r["t_end"]
        runs.append(r)
    out["B_ladder"] = runs

    # ---- A: chiral-on conservativity + echo variant ------------------
    print("A: chiral-on variant ...", flush=True)
    lam_try = [2000.0, 200.0, 20.0]
    chi = None
    chi_attempts = []
    for lam in lam_try:
        n, dt = (256, 0.002) if quick else (512, 0.001)
        try:
            r = run_2d_echo(n, L, dt, d, lam=lam, t_end=t_end_shared,
                            tag=f"chiral lam={lam}")
        except BlowUp as exc:
            print(f"  [chiral lam={lam}] BLEW UP: {exc}", flush=True)
            r = {"annihilated": False, "blown_up": True, "lam": lam}
        chi_attempts.append({"lam": lam,
                             "blown_up": bool(r.get("blown_up", False)),
                             "annihilated": bool(r.get("annihilated",
                                                       False)),
                             "energy_drift_rel":
                                 r.get("energy_drift_rel")})
        bad = (not r.get("annihilated")
               or not np.isfinite(r.get("fidelity_exact", np.nan))
               or r.get("energy_drift_rel", 1.0) > 0.3)
        if not bad:
            chi = r
            chi["lam_used"] = lam
            chi["lam_preregistered"] = 2000.0
            chi["deviation_note"] = (
                "" if lam == 2000.0 else
                f"lambda=2000 unstable at feasible dt (chiral advection "
                f"speed ~ lambda x core curl gradients); ran at the "
                f"largest stable lambda={lam}. The conservativity/"
                f"T-symmetry conclusion is lambda-independent (S1); "
                f"deviation recorded per rule 1.")
            break
    out["A_chiral"] = chi if chi is not None else {"failed": True}
    out["A_chiral_attempts"] = chi_attempts

    # ---- D: 3D ring reconnection echo --------------------------------
    print("D: 3D Hopf-link reconnection echo ...", flush=True)
    if quick:
        d_runs = [run_3d_echo(64, 48.0, 0.05, R=5.66, t_max=60.0,
                              tag="3D N=64")]
    else:
        d_runs = [run_3d_echo(64, 48.0, 0.05, R=5.66, t_max=120.0,
                              tag="3D N=64"),
                  run_3d_echo(96, 48.0, 0.034, R=5.66, t_max=120.0,
                              tag="3D N=96")]
    out["D_3d"] = d_runs

    # ---- verdicts ------------------------------------------------------
    lad = [r for r in runs if r.get("annihilated")]
    one_minus_F = [1.0 - r["fidelity_exact"] for r in lad]
    mono = all(one_minus_F[i + 1] <= one_minus_F[i]
               for i in range(len(one_minus_F) - 1))
    all_recovered = all(r["defects_recovered_exact"] for r in lad)
    f_finest = lad[-1]["fidelity_exact"] if lad else 0.0
    drift_ok = all(r["energy_drift_rel"] <= 1e-8 for r in lad)
    norm_ok = all(r["norm_drift_rel"] <= 1e-12 for r in lad)
    chiral_ok = bool(chi and chi.get("energy_drift_rel", 1) <= 1e-5
                     and chi.get("defects_recovered_exact"))
    # reconnection detection binds on the finest 3D run (the coarse
    # grid's core tube is marginally resolved); echo recovery binds on
    # every run
    d_ok = (d_runs[-1]["reconnection_observed"]
            and all(r["topology_recovered"] for r in d_runs))
    d_f_ok = (d_runs[-1]["fidelity_exact"] >= 0.95
              and (len(d_runs) < 2 or d_runs[-1]["fidelity_exact"]
                   >= d_runs[0]["fidelity_exact"]))
    mid_run = next(r for r in lad if r["n"] == mid)
    eps_star = max((e for e in eps_list
                    if mid_run.get(f"defects_recovered_eps{e:.0e}")),
                   default=0.0)
    out["verdicts"] = {
        "A_energy_drift_le_1e-8": bool(drift_ok),
        "A_norm_drift_le_1e-12": bool(norm_ok),
        "A_chiral_on_ok": chiral_ok,
        "B_defects_recovered_all_resolutions": bool(all_recovered),
        "B_one_minus_F_monotone_decreasing": bool(mono),
        "B_fidelity_finest": float(f_finest),
        "B_fidelity_finest_ge_0.99": bool(f_finest >= 0.99),
        "C_eps_star_largest_recovering": float(eps_star),
        "C_fidelity_curve": {f"{e:.0e}": mid_run.get(f"fidelity_eps{e:.0e}")
                             for e in eps_list},
        "D_reconnection_and_recovery": bool(d_ok),
        "D_fidelity_ok": bool(d_f_ok),
        "BRANCH_B_DEAD": bool(all_recovered and mono and f_finest >= 0.99
                              and d_ok),
        "S1_prediction": "conservative + T-symmetric => branch A; "
                         "exact echo recovers; branch B dead as written",
    }
    return out


def figure(out, dest):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        return None
    lad = [r for r in out["B_ladder"] if r.get("annihilated")]
    fig, axes = plt.subplots(1, 2, figsize=(9.2, 3.6))
    ax = axes[0]
    ns = [r["n"] for r in lad]
    ax.semilogy(ns, [max(1.0 - r["fidelity_exact"], 1e-16) for r in lad],
                "o-", label="exact echo $1-F$")
    ax.set_xlabel("grid N (dt halved with N)")
    ax.set_ylabel("$1-F$")
    ax.set_title("echo infidelity shrinks under refinement\n"
                 "(numerical, not dynamical)", fontsize=9)
    ax.legend(fontsize=8)
    ax = axes[1]
    cf = out["verdicts"]["C_fidelity_curve"]
    eps = sorted(float(k) for k in cf)
    ax.semilogx(eps, [cf[f"{e:.0e}"] for e in eps], "s-",
                label="perturbed-reversal fidelity")
    ax.set_xlabel(r"reversal perturbation $\varepsilon$")
    ax.set_ylabel("F")
    ax.set_title("recovery requires exact boundary data\n"
                 "(SSV-III sec. 8, measured)", fontsize=9)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(dest, dpi=160)
    plt.close(fig)
    return dest


def main():
    quick = "--quick" in sys.argv
    print(f"REVERSAL-ECHO S2, quick={quick}", flush=True)
    t0 = _time.time()
    out = battery(quick=quick)
    RESULTS.mkdir(parents=True, exist_ok=True)
    FIGURES.mkdir(parents=True, exist_ok=True)
    dest = RESULTS / ("reversal_echo_receipt_quick.json" if quick
                      else "reversal_echo_receipt.json")
    dest.write_text(json.dumps(out, indent=1))
    fig = figure(out, FIGURES / "reversal_echo_battery.png")
    print("\n--- verdicts ---")
    for k, v in out["verdicts"].items():
        print(f"  {k}: {v}")
    print(f"receipt -> {dest}")
    if fig:
        print(f"figure  -> {fig}")
    print(f"total {_time.time()-t0:.0f}s")


if __name__ == "__main__":
    main()
