"""Retrieve and index the primary sources used by the series-wide audit (#182).

The retrieved files are deliberately *not* tracked by git: this repository is
public and arXiv's distribution licence does not generally permit third-party
redistribution.  What is tracked is ``papers/cited/INDEX.md``, generated by this
script, which pins every source to an identifier, a URL, a SHA-256 and a
retrieval date.  Anyone can re-run this script and obtain byte-identical files.

Usage::

    python instruments/tools/fetch_cited.py            # fetch missing, regenerate index
    python instruments/tools/fetch_cited.py --verify   # verify hashes only, no network

A source that cannot be obtained openly is recorded in ``UNAVAILABLE`` with the
reason.  Paywalls are not circumvented; the dependent SSV claim is flagged
``PENDING-PRIMARY`` in the relevant damage report instead.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CITED = ROOT / "papers" / "cited"
PDF_DIR = CITED / "pdf"
TXT_DIR = CITED / "txt"
INDEX = CITED / "INDEX.md"

# Retrieval date of the initial audit sweep.  Kept explicit rather than derived
# from the clock so the generated index is reproducible.
RETRIEVED = "2026-07-27"

UA = "Mozilla/5.0 (SSV citation-audit; scholarly verification)"


@dataclass(frozen=True)
class Source:
    key: str
    author: str
    title: str
    venue: str
    ident: str
    url: str
    used_for: str
    verdict: str
    sha256_16: str = ""


@dataclass(frozen=True)
class Unavailable:
    key: str
    author: str
    title: str
    venue: str
    ident: str
    where: str
    status: str


#: Sources retrieved for the audit.  ``sha256_16`` pins the exact bytes that
#: were read; a mismatch means the upstream file changed and the verdict must
#: be re-checked against the new version.
SOURCES: list[Source] = [
    Source("volovik2001", "G. E. Volovik",
           "Superfluid analogies of cosmological phenomena",
           "Phys. Rept. 351, 195 (2001)", "arXiv:gr-qc/0005091",
           "https://arxiv.org/pdf/gr-qc/0005091",
           "SSV-I C1/C4/C5/C7",
           "MISATTRIBUTED (C4) — contains no logarithmic equation of state",
           "bcb49ad4530c588c"),
    Source("zloshchastiev2020", "K. G. Zloshchastiev",
           "Superfluid vacuum theory and deformed dispersion relations",
           "Int. J. Mod. Phys. A 35, 2040032 (2020)", "arXiv:2011.11897",
           "https://arxiv.org/pdf/2011.11897",
           "SSV-I C6; true source of the LogSE",
           "OK as cited — and is the ACTUAL source of the log nonlinearity",
           "8aff20eb75784f6d"),
    Source("barcelo2011", "C. Barcelo, S. Liberati, M. Visser",
           "Analogue gravity", "Living Rev. Relativ. 14, 3 (2011)",
           "arXiv:gr-qc/0505065", "https://arxiv.org/pdf/gr-qc/0505065",
           "SSV-I C2/C5/C6", "OK — Theorem 1 verbatim match",
           "78a12ecca7585522"),
    Source("hu2009", "B. L. Hu",
           "Emergent/quantum gravity: macro/micro structures of spacetime",
           "J. Phys. Conf. Ser. 174, 012015 (2009)", "arXiv:0903.0878",
           "https://arxiv.org/pdf/0903.0878", "SSV-I C3", "OK",
           "e4011d042e3fb22f"),
    Source("liberati2006", "S. Liberati, M. Sonego, M. Visser",
           "Analogue models for emergent gravity",
           "Class. Quant. Grav. 23, R167 (2006)", "arXiv:0909.3834",
           "https://arxiv.org/pdf/0909.3834", "SSV-I bibitem", "UNCITED",
           "cb85eb1c8b7a72cd"),
    Source("proment2012", "D. Proment, M. Onorato, C. F. Barenghi",
           "Vortex knots in a Bose-Einstein condensate",
           "Phys. Rev. E 85, 036306 (2012)", "arXiv:1110.5757",
           "https://arxiv.org/pdf/1110.5757", "SSV-I C9",
           "MISREAD — the trefoil is ONE closed curve, not three lines",
           "696d5dbfcfeb347b"),
    Source("faddeev1997", "L. Faddeev, A. J. Niemi", "Knots and Particles",
           "Nature 387, 58 (1997)", "arXiv:hep-th/9610193",
           "https://arxiv.org/pdf/hep-th/9610193", "SSV-I C8",
           "MISATTRIBUTED — zero occurrences of 'junction'",
           "e879864ec3a68faf"),
    Source("nitta2012_vortex_trimer", "M. Eto, M. Nitta",
           "Vortex trimer in three-component Bose-Einstein condensates",
           "Phys. Rev. A 85, 053645 (2012)", "arXiv:1201.0343",
           "https://arxiv.org/pdf/1201.0343",
           "SSV-I D2 resolution (new reference)",
           "A three-vortex junction requires 3 components + coherent coupling",
           "7df6d4e41ba88809"),
    Source("nitta2013_colorful_vortex_lattices", "M. Cipriani, M. Nitta",
           "Vortex lattices in three-component Bose-Einstein condensates under "
           "rotation: simulating colorful vortex lattices in a color superconductor",
           "arXiv only (published venue not verified)", "arXiv:1304.4375",
           "https://arxiv.org/pdf/1304.4375", "SSV-I D2 supporting",
           "Supporting — fractional vortices require multi-component structure",
           "c50e1fb651c5da0b"),
    Source("zloshchastiev2023_pramana_rotcurves", "K. G. Zloshchastiev",
           "Galaxy rotation curves in superfluid vacuum theory",
           "Pramana 97, 2 (2023)", "arXiv:2310.06861",
           "https://arxiv.org/pdf/2310.06861",
           "SSV-I C11 corroboration (NOT the cited work)",
           "No Bjerknes force (0 hits); G is an input, units G=1 -- both halves "
           "of the C11 claim contradicted",
           "34cb087f9019363d"),
    Source("polkinghorne2021", "R. E. S. Polkinghorne, A. J. Groszek, T. P. Simula",
           "Geometric phases of a vortex in a superfluid",
           "Phys. Rev. A 104, L041305 (2021)", "arXiv:2101.07438",
           "https://arxiv.org/pdf/2101.07438",
           "SSV-II C4/D3 -- open-access PROXY for the paywalled HaldaneWu1985",
           "Quotes, re-derives and numerically verifies Haldane-Wu: the phase "
           "counts enclosed ATOMS, not circulation quanta -> SSV-II MISREAD",
           "bb9eb1c160557019"),
    # NB: the arXiv preprint is titled "(Non)-universality of vortex
    # reconnections in superfluids"; it was RETITLED on publication.  That is
    # why the first bulk fetch's title search failed to resolve it.
    Source("Villois2017", "A. Villois, D. Proment, G. Krstulovic",
           "Universal and nonuniversal aspects of vortex reconnections in "
           "superfluids [arXiv title: '(Non)-universality of vortex "
           "reconnections in superfluids']",
           "Phys. Rev. Fluids 2, 044701 (2017)", "arXiv:1612.00386",
           "https://arxiv.org/pdf/1612.00386",
           "SSV-II C5 (main.tex:1091); SSV-III (duplicate key `Villois`)",
           "OK -- GP-model vortex reconnection, delta ~ (Gamma t)^1/2",
           "3e1dbf92fb867dc8"),
    Source("Clisby2010", "N. Clisby",
           "Accurate estimate of the critical exponent nu for self-avoiding "
           "walks via a fast implementation of the pivot algorithm",
           "Phys. Rev. Lett. 104, 055702 (2010)", "arXiv:1002.0494",
           "https://arxiv.org/pdf/1002.0494",
           "SSV-III main.tex:901 (SAW correlation-length exponent)",
           "OK -- nu = 0.587597(7), matches the quoted 0.587597 exactly",
           "cca34bb00b44c599"),
]

#: Sources that could not be obtained openly.  These are *not* verified, and
#: every SSV claim depending on them stays flagged in its damage report.
UNAVAILABLE: list[Unavailable] = [
    Unavailable("volovik2003", "G. E. Volovik", "The Universe in a Helium Droplet",
                "Oxford University Press (2003)", "ISBN 978-0198507826", "—",
                "PENDING-PRIMARY (book) — but C1 resolved `OK` via the volovik2001 "
                "proxy, which states it verbatim; C4/C7 stand as faults"),
    Unavailable("zloshchastiev2023", "K. G. Zloshchastiev",
                "Derivation of emergent spacetime metric, gravitational potential "
                "and speed of light in SVT", "Universe 9, 234 (2023)",
                "doi:10.3390/universe9050234",
                "https://www.mdpi.com/2218-1997/9/5/234",
                "PENDING-PRIMARY — HTTP 403 (open-access journal, bot filter). "
                "**Confirmed real via Crossref**, so SSV-I's bibitem is accurate. "
                "`MISATTRIBUTED` now expected: see "
                "notes/zloshchastiev2023_pramana_rotcurves.md — a closely-related "
                "2023 paper by the same author has 0 hits for Bjerknes and treats "
                "G as an input (units G=1)"),
    Unavailable("lamb1932", "H. Lamb", "Hydrodynamics, 6th ed., §163",
                "Cambridge University Press (1932)", "—",
                "https://archive.org/details/dli.ernet.3284",
                "**RESOLVED `OK`** — OCR unusable for mathematics, but Arts. 162-163 "
                "(pp.239-241) were read from owner-supplied page images and "
                "transcribed verbatim in notes/lamb1932.verbatim.md. Art. 163 (6) "
                "gives T = 1/2 rho kappa^2 R [log(8R/a) - 7/4], matching SSV-I "
                "eq:Ekin exactly"),
    Unavailable("HaldaneWu1985", "F. D. M. Haldane, Y.-S. Wu",
                "Quantum dynamics and statistics of vortices in two-dimensional "
                "superfluids", "Phys. Rev. Lett. 55, 2887 (1985)",
                "doi:10.1103/PhysRevLett.55.2887",
                "https://link.aps.org/doi/10.1103/PhysRevLett.55.2887",
                "**RESOLVED `MISREAD`** — pre-arXiv and paywalled, not obtained. "
                "Settled via the open-access proxy notes/polkinghorne2021.md, "
                "which quotes, re-derives AND numerically verifies the result: "
                "gamma_C = 2*pi*N_C counts the enclosed CONDENSATE ATOMS, not the "
                "'circulation quanta' SSV-II main.tex:832 attributes to it"),
    Unavailable("stone2005", "M. Stone",
                "Phonons in a BEC as an example of an emergent phenomenon",
                "Phys. Rev. D 71, 085007 (2005)", "—", "—",
                "UNCITED; no arXiv match found"),
]


def sha16(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def fetch(src: Source) -> tuple[str, str]:
    """Return ``(state, detail)`` for one source."""
    dest = PDF_DIR / f"{src.key}.pdf"
    if dest.exists():
        got = sha16(dest)
        if src.sha256_16 and got != src.sha256_16:
            return "HASH-MISMATCH", f"expected {src.sha256_16}, got {got}"
        return "cached", got
    req = urllib.request.Request(src.url, headers={"User-Agent": UA})
    try:
        blob = urllib.request.urlopen(req, timeout=60).read()
    except Exception as exc:  # network/publisher failure is a recorded state
        return "FAIL", str(exc)
    if blob[:4] != b"%PDF":
        return "FAIL", f"not a PDF (starts {blob[:16]!r})"
    PDF_DIR.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(blob)
    got = sha16(dest)
    if src.sha256_16 and got != src.sha256_16:
        return "HASH-MISMATCH", f"expected {src.sha256_16}, got {got}"
    return "fetched", got


def render_index() -> str:
    out: list[str] = []
    add = out.append
    add("# Retrieved sources for the series-wide citation audit (#182)\n")
    add("Generated by `instruments/tools/fetch_cited.py` — do not edit by hand.\n")
    add("Primary sources retrieved to verify load-bearing citations. **The files")
    add("themselves are not tracked**: this repository is public and arXiv's")
    add("distribution licence does not generally permit third-party redistribution.")
    add("Everything needed to reproduce the audit is here — fetch the identifier,")
    add("verify the SHA-256, and you hold the identical file that was read.\n")
    add("Local (gitignored) layout: `pdf/<key>.pdf`, `txt/<key>.txt`.")
    add("Short verbatim quotations used as evidence are tracked in `notes/<key>.md`.\n")
    add("Re-fetch with `python instruments/tools/fetch_cited.py`;")
    add("check bytes without touching the network with `--verify`.\n")
    add("## Evidence rule\n")
    add("**No C-gate verdict without a verbatim quotation.** Every row below links")
    add("to `notes/<key>.md`, which reproduces the actual paragraph or equation the")
    add("verdict rests on. A reader can therefore check any verdict in this audit")
    add("without re-downloading anything — which is precisely what was missing when")
    add("the faults recorded in #183 were introduced.\n")
    add("## Retrieved\n")
    add("| key | author | work | id | SHA-256 (16) | retrieved | used for | verdict | evidence |")
    add("|---|---|---|---|---|---|---|---|---|")
    for s in SOURCES:
        ev = f"[quote](notes/{s.key}.md)" if (CITED / "notes" / f"{s.key}.md").exists() else "**missing**"
        add(f"| `{s.key}` | {s.author} | *{s.title}*, {s.venue} | "
            f"[{s.ident}]({s.url}) | `{s.sha256_16}` | {RETRIEVED} | "
            f"{s.used_for} | {s.verdict} | {ev} |")
    add("\n## Not retrieved, or retrieved but not machine-verifiable\n")
    add("These are **not** treated as verified. Any SSV claim depending on them stays")
    add("flagged `PENDING-PRIMARY` in its damage report. Paywalls are not")
    add("circumvented, and equations are never read off degraded OCR.\n")
    add("| key | author | work | id | where | status | evidence |")
    add("|---|---|---|---|---|---|---|")
    for u in UNAVAILABLE:
        where = f"[link]({u.where})" if u.where != "—" else "—"
        ev = f"[detail](notes/{u.key}.md)" if (CITED / "notes" / f"{u.key}.md").exists() else "**missing**"
        add(f"| `{u.key}` | {u.author} | *{u.title}*, {u.venue} | {u.ident} | "
            f"{where} | {u.status} | {ev} |")
    add("")
    return "\n".join(out)


def missing_evidence() -> list[str]:
    """Keys carrying a verdict but no tracked quotation. Must stay empty."""
    keys = [s.key for s in SOURCES] + [u.key for u in UNAVAILABLE]
    return [k for k in keys if not (CITED / "notes" / f"{k}.md").exists()]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--verify", action="store_true",
                    help="verify local hashes only; do not use the network")
    args = ap.parse_args()

    bad = 0
    for src in SOURCES:
        dest = PDF_DIR / f"{src.key}.pdf"
        if args.verify:
            if not dest.exists():
                print(f"{src.key:38s} MISSING")
                bad += 1
                continue
            got = sha16(dest)
            ok = got == src.sha256_16
            print(f"{src.key:38s} {'ok' if ok else 'HASH-MISMATCH'} {got}")
            bad += 0 if ok else 1
        else:
            state, detail = fetch(src)
            print(f"{src.key:38s} {state:14s} {detail}")
            bad += state in ("FAIL", "HASH-MISMATCH")

    for u in UNAVAILABLE:
        print(f"{u.key:38s} {'unavailable':14s} {u.status}")

    INDEX.write_text(render_index())
    print(f"\nwrote {INDEX.relative_to(ROOT)}")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
