"""Retrieve and index the primary sources used by the series-wide audit (#182).

The retrieved files are deliberately *not* tracked by git: this repository is
public and arXiv's distribution licence does not generally permit third-party
redistribution.  What is tracked is ``papers/cited/verification.json`` plus
``papers/cited/INDEX.md``, generated by this script.  Together they pin every
source to identifiers, a URL, a SHA-256, an access state and a verification
status.  Anyone can re-run this script and obtain byte-identical files.

Usage::

    python instruments/tools/fetch_cited.py            # fetch missing, regenerate index
    python instruments/tools/fetch_cited.py --verify   # verify hashes only, no network

A source that cannot be obtained openly is recorded in ``UNAVAILABLE`` with the
reason.  Paywalls are not circumvented; the dependent SSV claim is flagged
``PENDING-PRIMARY`` in the relevant damage report instead.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CITED = ROOT / "papers" / "cited"
PDF_DIR = CITED / "pdf"
TXT_DIR = CITED / "txt"
INDEX = CITED / "INDEX.md"
VERIFICATION = CITED / "verification.json"

# Retrieval date of the initial audit sweep.  Kept explicit rather than derived
# from the clock so the generated index is reproducible.
RETRIEVED = "2026-07-28"

UA = "Mozilla/5.0 (SSV citation-audit; scholarly verification)"


@dataclass(frozen=True)
class Source:
    key: str
    author: str
    title: str
    venue: str
    ident: str
    url: str
    used_for: str
    verdict: str
    sha256_16: str = ""


@dataclass(frozen=True)
class Unavailable:
    key: str
    author: str
    title: str
    venue: str
    ident: str
    where: str
    status: str


#: Sources retrieved for the audit.  ``sha256_16`` pins the exact bytes that
#: were read; a mismatch means the upstream file changed and the verdict must
#: be re-checked against the new version.
SOURCES: list[Source] = [
    Source("volovik2001", "G. E. Volovik",
           "Superfluid analogies of cosmological phenomena",
           "Phys. Rept. 351, 195 (2001)", "arXiv:gr-qc/0005091",
           "https://arxiv.org/pdf/gr-qc/0005091",
           "SSV-I C1/C4/C5/C7",
           "MISATTRIBUTED (C4) — contains no logarithmic equation of state",
           "bcb49ad4530c588c"),
    Source("zloshchastiev2020", "K. G. Zloshchastiev",
           "Superfluid vacuum theory and deformed dispersion relations",
           "Int. J. Mod. Phys. A 35, 2040032 (2020)", "arXiv:2011.11897",
           "https://arxiv.org/pdf/2011.11897",
           "SSV-I C6; true source of the LogSE",
           "OK as cited — and is the ACTUAL source of the log nonlinearity",
           "8aff20eb75784f6d"),
    Source("barcelo2011", "C. Barcelo, S. Liberati, M. Visser",
           "Analogue gravity", "Living Rev. Relativ. 14, 3 (2011)",
           "arXiv:gr-qc/0505065", "https://arxiv.org/pdf/gr-qc/0505065",
           "SSV-I C2/C5/C6", "OK — Theorem 1 verbatim match",
           "78a12ecca7585522"),
    Source("hu2009", "B. L. Hu",
           "Emergent/quantum gravity: macro/micro structures of spacetime",
           "J. Phys. Conf. Ser. 174, 012015 (2009)", "arXiv:0903.0878",
           "https://arxiv.org/pdf/0903.0878", "SSV-I C3", "OK",
           "e4011d042e3fb22f"),
    Source("proment2012", "D. Proment, M. Onorato, C. F. Barenghi",
           "Vortex knots in a Bose-Einstein condensate",
           "Phys. Rev. E 85, 036306 (2012)", "arXiv:1110.5757",
           "https://arxiv.org/pdf/1110.5757", "SSV-I C9",
           "MISREAD — the trefoil is ONE closed curve, not three lines",
           "696d5dbfcfeb347b"),
    Source("faddeev1997", "L. Faddeev, A. J. Niemi", "Knots and Particles",
           "Nature 387, 58 (1997)", "arXiv:hep-th/9610193",
           "https://arxiv.org/pdf/hep-th/9610193", "SSV-I C8",
           "MISATTRIBUTED — zero occurrences of 'junction'",
           "e879864ec3a68faf"),
    Source("nitta2012_vortex_trimer", "M. Eto, M. Nitta",
           "Vortex trimer in three-component Bose-Einstein condensates",
           "Phys. Rev. A 85, 053645 (2012)", "arXiv:1201.0343",
           "https://arxiv.org/pdf/1201.0343",
           "SSV-I D2 resolution (new reference)",
           "A three-vortex junction requires 3 components + coherent coupling",
           "7df6d4e41ba88809"),
    Source("nitta2013_colorful_vortex_lattices", "M. Cipriani, M. Nitta",
           "Vortex lattices in three-component Bose-Einstein condensates under "
           "rotation: simulating colorful vortex lattices in a color superconductor",
           "Phys. Rev. A 88, 013634 (2013)", "arXiv:1304.4375",
           "https://arxiv.org/pdf/1304.4375", "SSV-I D2 supporting",
           "Supporting — fractional vortices require multi-component structure",
           "c50e1fb651c5da0b"),
    Source("zloshchastiev2023_pramana_rotcurves", "K. G. Zloshchastiev",
           "Galaxy rotation curves in superfluid vacuum theory",
           "Pramana 97, 2 (2023)", "arXiv:2310.06861",
           "https://arxiv.org/pdf/2310.06861",
           "SSV-I C11 corroboration (NOT the cited work)",
           "OK as corroboration -- no Bjerknes force (0 hits); G is an input, "
           "units G=1",
           "34cb087f9019363d"),
    Source("polkinghorne2021", "R. E. S. Polkinghorne, A. J. Groszek, T. P. Simula",
           "Geometric phases of a vortex in a superfluid",
           "Phys. Rev. A 104, L041305 (2021)", "arXiv:2101.07438",
           "https://arxiv.org/pdf/2101.07438",
           "SSV-II C4/D3 -- open-access PROXY for the paywalled HaldaneWu1985",
           "Quotes, re-derives and numerically verifies Haldane-Wu: the phase "
           "counts enclosed ATOMS, not circulation quanta -> SSV-II MISREAD",
           "bb9eb1c160557019"),
    # NB: the arXiv preprint is titled "(Non)-universality of vortex
    # reconnections in superfluids"; it was RETITLED on publication.  That is
    # why the first bulk fetch's title search failed to resolve it.
    Source("Villois2017", "A. Villois, D. Proment, G. Krstulovic",
           "Universal and nonuniversal aspects of vortex reconnections in "
           "superfluids [arXiv title: '(Non)-universality of vortex "
           "reconnections in superfluids']",
           "Phys. Rev. Fluids 2, 044701 (2017)", "arXiv:1612.00386",
           "https://arxiv.org/pdf/1612.00386",
           "SSV-II C5 (main.tex:1091); SSV-III (duplicate key `Villois`)",
           "OK -- GP-model vortex reconnection, delta ~ (Gamma t)^1/2",
           "3e1dbf92fb867dc8"),
    Source("Clisby2010", "N. Clisby",
           "Accurate estimate of the critical exponent nu for self-avoiding "
           "walks via a fast implementation of the pivot algorithm",
           "Phys. Rev. Lett. 104, 055702 (2010)", "arXiv:1002.0494",
           "https://arxiv.org/pdf/1002.0494",
           "SSV-III main.tex:901 (SAW correlation-length exponent)",
           "OK -- nu = 0.587597(7), matches the quoted 0.587597 exactly",
           "cca34bb00b44c599"),
    Source("zloshchastiev2023", "K. G. Zloshchastiev",
           "Derivation of emergent spacetime metric, gravitational potential "
           "and speed of light in superfluid vacuum theory",
           "Universe 9, 234 (2023)", "doi:10.3390/universe9050234",
           "https://inspirehep.net/files/0715887b217e080940b04b34bbbf375e",
           "SSV-I C11",
           "MISATTRIBUTED -- no Bjerknes mechanism and no derivation of G from "
           "hbar, c, electron mass and alpha",
           "d80609424b0e3774"),
]

#: Sources that could not be obtained openly.  These are *not* verified, and
#: every SSV claim depending on them stays flagged in its damage report.
UNAVAILABLE: list[Unavailable] = [
    Unavailable("volovik2003", "G. E. Volovik", "The Universe in a Helium Droplet",
                "Oxford University Press (2003)", "ISBN 978-0198507826", "—",
                "PENDING-PRIMARY (book) — but C1 resolved `OK` via the volovik2001 "
                "proxy, which states it verbatim; C4/C7 stand as faults"),
    Unavailable("lamb1932", "H. Lamb", "Hydrodynamics, 6th ed., §163",
                "Cambridge University Press (1932)", "—",
                "https://archive.org/details/dli.ernet.3284",
                "**RESOLVED `OK`** — OCR unusable for mathematics, but Arts. 162-163 "
                "(pp.239-241) were read from owner-supplied page images and "
                "transcribed verbatim in transcripts/lamb1932.md. Art. 163 (6) "
                "gives T = 1/2 rho kappa^2 R [log(8R/a) - 7/4], matching SSV-I "
                "eq:Ekin exactly"),
    Unavailable("HaldaneWu1985", "F. D. M. Haldane, Y.-S. Wu",
                "Quantum dynamics and statistics of vortices in two-dimensional "
                "superfluids", "Phys. Rev. Lett. 55, 2887 (1985)",
                "doi:10.1103/PhysRevLett.55.2887",
                "https://link.aps.org/doi/10.1103/PhysRevLett.55.2887",
                "**RESOLVED `MISREAD`** — pre-arXiv and paywalled, not obtained. "
                "Settled via the open-access proxy notes/polkinghorne2021.md, "
                "which quotes, re-derives AND numerically verifies the result: "
                "gamma_C = 2*pi*N_C counts the enclosed CONDENSATE ATOMS, not the "
                "'circulation quanta' SSV-II main.tex:832 attributes to it"),
]


def sha16(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def fetch(src: Source) -> tuple[str, str]:
    """Return ``(state, detail)`` for one source."""
    dest = PDF_DIR / f"{src.key}.pdf"
    if dest.exists():
        got = sha16(dest)
        if src.sha256_16 and got != src.sha256_16:
            return "HASH-MISMATCH", f"expected {src.sha256_16}, got {got}"
        return "cached", got
    req = urllib.request.Request(src.url, headers={"User-Agent": UA})
    try:
        blob = urllib.request.urlopen(req, timeout=60).read()
    except Exception as exc:  # network/publisher failure is a recorded state
        return "FAIL", str(exc)
    if blob[:4] != b"%PDF":
        return "FAIL", f"not a PDF (starts {blob[:16]!r})"
    PDF_DIR.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(blob)
    got = sha16(dest)
    if src.sha256_16 and got != src.sha256_16:
        return "HASH-MISMATCH", f"expected {src.sha256_16}, got {got}"
    return "fetched", got


def render_index() -> str:
    registry = json.loads(VERIFICATION.read_text(encoding="utf-8"))["sources"]

    def ids_for(key: str) -> str:
        identifiers = registry[key]["identifiers"]
        links: list[str] = []
        if identifiers["doi_status"] == "present":
            doi = identifiers["doi"]
            links.append(f"[doi:{doi}](https://doi.org/{doi})")
        if identifiers["arxiv_status"] == "present":
            arxiv = identifiers["arxiv"]
            links.append(f"[arXiv:{arxiv}](https://arxiv.org/abs/{arxiv})")
        for name, value in identifiers.get("other", {}).items():
            links.append(f"{name}:{value}")
        return "<br>".join(links) or "none known"

    def source_for(key: str) -> str:
        return f"[source]({registry[key]['source_url']})"

    out: list[str] = []
    add = out.append
    add("# Retrieved sources for the series-wide citation audit (#182)\n")
    add("Generated by `instruments/tools/fetch_cited.py` — do not edit by hand.\n")
    add("Primary sources retrieved to verify load-bearing citations. **The files")
    add("themselves are not tracked**: this repository is public and arXiv's")
    add("distribution licence does not generally permit third-party redistribution.")
    add("Everything needed to reproduce the audit is here — fetch the identifier,")
    add("verify the SHA-256, and you hold the identical file that was read.\n")
    add("Local (gitignored) layout: `pdf/<key>.pdf`, `txt/<key>.txt`.")
    add("Canonical bibliographic entries for the complete series are in")
    add("`references.bib`; BibTeX selects the subset cited by each paper.")
    add("Identifiers, access states, paragraph requirements and verification")
    add("statuses are canonical in `verification.json`. Claim-specific")
    add("quotations and use assessments are tracked in")
    add("`notes/<key>.md`; accessible transcriptions of image-only source pages")
    add("are tracked separately in `transcripts/<key>.md`.\n")
    add("Re-fetch with `python instruments/tools/fetch_cited.py`;")
    add("check bytes without touching the network with `--verify`.\n")
    add("## Evidence rule\n")
    add("**Paragraph evidence is required by default.** Every row below links")
    add("to `notes/<key>.md`, which identifies the SSV claim, reproduces the")
    add("complete source paragraph, gives a page/section locator, and assesses")
    add("whether the source is used correctly. A paragraph-free record passes")
    add("only when `verification.json` contains a validated, reasoned exception")
    add("(an inaccessible primary or a reproducible full-source absence search).")
    add("A reader can therefore check any verdict in this audit")
    add("without re-downloading anything — which is precisely what was missing when")
    add("the faults recorded in #183 were introduced.\n")
    add("## Retrieved\n")
    add("| key | author | work | identifiers | source | SHA-256 (16) | retrieved | used for | verdict | evidence |")
    add("|---|---|---|---|---|---|---|---|---|---|")
    for s in SOURCES:
        ev = f"[quote](notes/{s.key}.md)" if (CITED / "notes" / f"{s.key}.md").exists() else "**missing**"
        add(f"| `{s.key}` | {s.author} | *{s.title}*, {s.venue} | "
            f"{ids_for(s.key)} | {source_for(s.key)} | `{s.sha256_16}` | "
            f"{RETRIEVED} | "
            f"{s.used_for} | {s.verdict} | {ev} |")
    add("\n## Not retrieved, or retrieved but not machine-verifiable\n")
    add("These primaries cannot be read as ordinary extracted PDFs. Their explicit")
    add("paragraph exceptions and unresolved status are recorded in")
    add("`verification.json`; a proxy or accessible scan transcript may resolve a")
    add("specific claim. Paywalls are not circumvented, and equations are never")
    add("read off degraded OCR.\n")
    add("| key | author | work | identifiers | source | status | evidence |")
    add("|---|---|---|---|---|---|---|")
    for u in UNAVAILABLE:
        ev = f"[detail](notes/{u.key}.md)" if (CITED / "notes" / f"{u.key}.md").exists() else "**missing**"
        add(f"| `{u.key}` | {u.author} | *{u.title}*, {u.venue} | "
            f"{ids_for(u.key)} | {source_for(u.key)} | {u.status} | {ev} |")
    add("")
    return "\n".join(out)


def missing_evidence() -> list[str]:
    """Structural or traceability defects in citation evidence. Must stay empty."""
    # Lazy import avoids a module cycle: citation_evidence uses the source
    # registry above to decide which notes must exist.
    import citation_evidence
    return citation_evidence.evidence_issues()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--verify", action="store_true",
                    help="verify local hashes only; do not use the network")
    args = ap.parse_args()

    bad = 0
    for src in SOURCES:
        dest = PDF_DIR / f"{src.key}.pdf"
        if args.verify:
            if not dest.exists():
                print(f"{src.key:38s} MISSING")
                bad += 1
                continue
            got = sha16(dest)
            ok = got == src.sha256_16
            print(f"{src.key:38s} {'ok' if ok else 'HASH-MISMATCH'} {got}")
            bad += 0 if ok else 1
        else:
            state, detail = fetch(src)
            print(f"{src.key:38s} {state:14s} {detail}")
            bad += state in ("FAIL", "HASH-MISMATCH")

    for u in UNAVAILABLE:
        print(f"{u.key:38s} {'unavailable':14s} {u.status}")

    evidence = missing_evidence()
    for issue in evidence:
        print(f"{'citation evidence':38s} FAIL           {issue}")
    bad += bool(evidence)

    INDEX.write_text(render_index(), encoding="utf-8")
    import citation_evidence
    citation_evidence.write_note_index()
    print(f"\nwrote {INDEX.relative_to(ROOT)}")
    print(f"wrote {citation_evidence.NOTE_INDEX.relative_to(ROOT)}")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
