"""Thin-ring alpha-correction diagnostic for the muon helicity bridge.

Status: prototype
Problem type: analytic/numerical checkpoint
Nondimensionalisation: xi = 1, R_e / xi = alpha^{-1}

This script checks angular pieces of the first finite-alpha correction to the
helicity-projected current-curl bridge described in
papers/SSV-I/thin-ring-muon-feasibility-memo.md.

It deliberately does not claim to evaluate the full BdG second variation. The
goal is narrower: verify parity selections that make common straight-core
geometric and curl-operator O(alpha) terms vanish before any radial integrals
are attempted.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from typing import Callable


TWO_PI = 2.0 * math.pi


def angular_moment(power: int) -> float:
    """Return integral_0^{2pi} cos(theta)^power dtheta for non-negative power."""
    if power < 0:
        raise ValueError("power must be non-negative")
    if power % 2 == 1:
        return 0.0
    if power == 0:
        return TWO_PI
    # Integral cos^(2n) over a full period is 2*pi*(2n)!/(2^(2n)(n!)^2).
    n = power // 2
    return TWO_PI * math.factorial(2 * n) / ((2.0 ** (2 * n)) * (math.factorial(n) ** 2))


@dataclass(frozen=True)
class FactorCorrection:
    factor_power: float
    name: str
    c1_per_x: float
    c2_per_x2: float
    interpretation: str


@dataclass(frozen=True)
class OperatorTerm:
    name: str
    projection: float
    normalized_to_leading: float
    interpretation: str


@dataclass(frozen=True)
class FiniteAlphaScanRow:
    alpha: float
    ring_radius: float
    chi_to_kelvin_abs: float
    r_to_kelvin_abs: float
    chi_relative_to_first: float
    r_relative_to_first: float


@dataclass(frozen=True)
class FiniteAlphaScan:
    rows: list[FiniteAlphaScanRow]
    chi_relative_slope: float
    r_relative_slope: float
    interpretation: str


def correction_for_factor(power: float, name: str) -> FactorCorrection:
    """Expansion of angular projection with metric factor (1+eps*x*cos)^power.

    The leading helicity bridge angular integral is proportional to

        (1/4) integral cos(theta)^2 dtheta = pi/4.

    A straight-core geometric factor contributes

        (1 + eps*x*cos(theta))^p
        = 1 + p eps*x*cos(theta)
          + p(p-1)/2 eps^2*x^2*cos(theta)^2 + ...

    The O(eps) term is proportional to integral cos^3(theta), which vanishes.
    """
    leading = angular_moment(2)
    c1_per_x = power * angular_moment(3) / leading
    c2_per_x2 = 0.5 * power * (power - 1.0) * angular_moment(4) / leading
    if abs(c1_per_x) < 1.0e-14:
        interpretation = "no O(alpha) correction by angular parity"
    else:
        interpretation = "O(alpha) correction survives"
    return FactorCorrection(
        factor_power=power,
        name=name,
        c1_per_x=c1_per_x,
        c2_per_x2=c2_per_x2,
        interpretation=interpretation,
    )


def integrate_periodic(func: Callable[[float], float], n: int = 20000) -> float:
    """Midpoint integral on [0, 2*pi). Exact enough for parity diagnostics."""
    h = TWO_PI / n
    return sum(func((i + 0.5) * h) for i in range(n)) * h


def dtheta_cos(theta: float) -> float:
    return -math.sin(theta)


def dtheta_sin(theta: float) -> float:
    return math.cos(theta)


def operator_projection(
    right: Callable[[float], float],
    op: Callable[[float, Callable[[float], float]], float],
    leading: float,
) -> float:
    """Project an O(alpha) operator against the leading even helicity channel.

    The leading pi/4 bridge uses (1/4) int cos(theta)^2 dtheta. We model the
    relevant even channel by using cos(theta) on the left and right. The tested
    operators are the angular building blocks generated by expanding the
    orthogonal-coordinate curl with h_phi = R_e + rho cos(theta).
    """
    value = integrate_periodic(lambda theta: math.cos(theta) * op(theta, right))
    return value / leading


def run_operator_terms() -> list[OperatorTerm]:
    leading = angular_moment(2)

    def right_cos(theta: float) -> float:
        return math.cos(theta)

    def op_cos_multiplier(theta: float, right: Callable[[float], float]) -> float:
        return math.cos(theta) * right(theta)

    def op_sin_multiplier(theta: float, right: Callable[[float], float]) -> float:
        return math.sin(theta) * right(theta)

    def op_cos_dtheta(theta: float, right: Callable[[float], float]) -> float:
        # For the leading even channel, d/dtheta cos(theta) = -sin(theta).
        del right
        return math.cos(theta) * dtheta_cos(theta)

    def op_sin_dtheta(theta: float, right: Callable[[float], float]) -> float:
        del right
        return math.sin(theta) * dtheta_cos(theta)

    raw_terms = [
        ("cos(theta) multiplier from 1/h_phi expansion", op_cos_multiplier),
        ("sin(theta) multiplier from d_theta h_phi", op_sin_multiplier),
        ("cos(theta) d_theta term", op_cos_dtheta),
        ("sin(theta) d_theta term", op_sin_dtheta),
    ]
    terms: list[OperatorTerm] = []
    for name, op in raw_terms:
        normalized = operator_projection(right_cos, op, leading)
        projection = normalized * leading
        if abs(normalized) < 1.0e-12:
            interpretation = "vanishes against leading even channel"
        else:
            interpretation = "survives; requires full radial/operator check"
        terms.append(
            OperatorTerm(
                name=name,
                projection=projection,
                normalized_to_leading=normalized,
                interpretation=interpretation,
            )
        )
    return terms


@dataclass(frozen=True)
class DiagnosticResult:
    leading_angular_integral: float
    helicity_factor: float
    bdg_symmetrization_factor: float
    leading_bridge_factor: float
    integral_cos3: float
    first_order_verdict: str
    factor_corrections: list[FactorCorrection]
    operator_terms: list[OperatorTerm]
    operator_verdict: str
    finite_alpha_scan: FiniteAlphaScan | None
    curved_background_scan: FiniteAlphaScan | None


def fit_slope(xs: list[float], ys: list[float]) -> float:
    if len(xs) < 2:
        return 0.0
    x_bar = sum(xs) / len(xs)
    y_bar = sum(ys) / len(ys)
    denom = sum((x - x_bar) ** 2 for x in xs)
    if denom == 0.0:
        return 0.0
    return sum((x - x_bar) * (y - y_bar) for x, y in zip(xs, ys)) / denom


def run_finite_alpha_scan(
    alphas: list[float],
    n: int,
    half_width: float,
    profile: str,
    profile_n: int,
    profile_x_max: float,
) -> FiniteAlphaScan:
    """Use existing current-curl machinery to check raw overlap drift with alpha.

    This is still a reduced diagnostic: it uses a straight-core profile and the
    existing normalized helicity modes. Its job is only to catch an obvious
    finite-radius linear drift that the angular parity table might have missed.
    """
    return run_current_curl_scan(alphas, n, half_width, (), (), profile, profile_n, profile_x_max)


def run_current_curl_scan(
    alphas: list[float],
    n: int,
    half_width: float,
    curvature_coeffs: tuple[float, ...],
    phase_coeffs: tuple[float, ...],
    profile: str,
    profile_n: int,
    profile_x_max: float,
) -> FiniteAlphaScan:
    """Run the same finite-alpha scan with optional curved-background terms."""
    from chiral_bridge_projection import chiral_overlap
    from kelvin_augmented_bdg import build_modes
    from toroidal_background import CurvedToroidalBackground, ToroidalBackground
    from toroidal_projection_integrals import ProjectionConfig
    from vortex_profile import VortexProfile

    cfg = ProjectionConfig(
        n=n,
        half_width=half_width,
        profile=profile,
        profile_n=profile_n,
        profile_x_max=profile_x_max,
        chi_parity="sin",
    )
    vortex = VortexProfile.solve(n=profile_n, x_max=profile_x_max) if profile == "numerical" else None
    rows: list[FiniteAlphaScanRow] = []
    first_chi = None
    first_r = None
    for alpha in alphas:
        if curvature_coeffs or phase_coeffs:
            kwargs = (
                {"f0": vortex.value, "f0_prime": vortex.derivative}
                if vortex is not None
                else {}
            )
            bg = CurvedToroidalBackground(
                alpha=alpha,
                curvature_coeffs=curvature_coeffs,
                phase_coeffs=phase_coeffs,
                **kwargs,
            )
        else:
            bg = (
                ToroidalBackground(alpha=alpha, f0=vortex.value, f0_prime=vortex.derivative)
                if vortex is not None
                else ToroidalBackground(alpha=alpha)
            )
        modes = build_modes(bg, cfg, include_core_four=False, kelvin_seed="helicity")
        by_name = {mode.name: mode for mode in modes}
        kelvin = by_name["K_helicity_plus_plus"]
        chi_abs = abs(chiral_overlap(bg, by_name["chi"], kelvin, cfg))
        r_abs = abs(chiral_overlap(bg, by_name["R"], kelvin, cfg))
        first_chi = chi_abs if first_chi is None else first_chi
        first_r = r_abs if first_r is None else first_r
        rows.append(
            FiniteAlphaScanRow(
                alpha=alpha,
                ring_radius=bg.r_e,
                chi_to_kelvin_abs=chi_abs,
                r_to_kelvin_abs=r_abs,
                chi_relative_to_first=chi_abs / first_chi if first_chi else 1.0,
                r_relative_to_first=r_abs / first_r if first_r else 1.0,
            )
        )
    xs = [row.alpha for row in rows]
    chi_slope = fit_slope(xs, [row.chi_relative_to_first for row in rows])
    r_slope = fit_slope(xs, [row.r_relative_to_first for row in rows])
    if abs(chi_slope) < 1.0e-8 and abs(r_slope) < 1.0e-8:
        interpretation = f"normalized {profile}-profile overlaps show no detectable linear alpha drift"
    elif curvature_coeffs or phase_coeffs:
        interpretation = f"curved-background {profile}-profile ansatz shows alpha drift; relaxed background is a real remaining risk"
    else:
        interpretation = "finite-alpha scan shows a detectable linear drift; inspect before trusting parity"
    return FiniteAlphaScan(
        rows=rows,
        chi_relative_slope=chi_slope,
        r_relative_slope=r_slope,
        interpretation=interpretation,
    )


def run_diagnostic(
    extra_powers: list[float],
    include_finite_alpha_scan: bool,
    scan_alphas: list[float],
    scan_n: int,
    scan_half_width: float,
    curvature_coeffs: tuple[float, ...],
    phase_coeffs: tuple[float, ...],
    scan_profile: str,
    scan_profile_n: int,
    scan_profile_x_max: float,
) -> DiagnosticResult:
    helicity_factor = 0.5
    bdg_symmetrization_factor = 0.5
    leading_angular = angular_moment(2)
    leading_bridge = helicity_factor * bdg_symmetrization_factor * leading_angular
    powers = [
        (1.0, "Jacobian r = R_e + rho cos(theta)"),
        (-1.0, "single inverse-radius factor"),
        (-2.0, "two inverse-radius factors"),
    ]
    powers.extend((power, f"user factor power {power:g}") for power in extra_powers)
    corrections = [correction_for_factor(power, name) for power, name in powers]
    first_order_ok = all(abs(row.c1_per_x) < 1.0e-14 for row in corrections)
    operator_terms = run_operator_terms()
    operator_ok = all(abs(row.normalized_to_leading) < 1.0e-12 for row in operator_terms)
    verdict = (
        "pure straight-core metric/Jacobian factors do not shift pi/4 at O(alpha)"
        if first_order_ok
        else "at least one requested factor has an O(alpha) angular correction"
    )
    operator_verdict = (
        "standard O(alpha) curl angular building blocks vanish against the leading even channel"
        if operator_ok
        else "some O(alpha) curl angular building blocks survive this parity test"
    )
    return DiagnosticResult(
        leading_angular_integral=leading_angular,
        helicity_factor=helicity_factor,
        bdg_symmetrization_factor=bdg_symmetrization_factor,
        leading_bridge_factor=leading_bridge,
        integral_cos3=angular_moment(3),
        first_order_verdict=verdict,
        factor_corrections=corrections,
        operator_terms=operator_terms,
        operator_verdict=operator_verdict,
        finite_alpha_scan=run_finite_alpha_scan(
            scan_alphas,
            scan_n,
            scan_half_width,
            scan_profile,
            scan_profile_n,
            scan_profile_x_max,
        )
        if include_finite_alpha_scan
        else None,
        curved_background_scan=run_current_curl_scan(
            scan_alphas,
            scan_n,
            scan_half_width,
            curvature_coeffs,
            phase_coeffs,
            scan_profile,
            scan_profile_n,
            scan_profile_x_max,
        )
        if include_finite_alpha_scan and (curvature_coeffs or phase_coeffs)
        else None,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check the angular parity of finite-alpha thin-ring bridge corrections."
    )
    parser.add_argument(
        "--extra-factor-powers",
        default="",
        help="Comma-separated extra powers p for factors (1+alpha*x*cos(theta))^p.",
    )
    parser.add_argument("--finite-alpha-scan", action="store_true", help="Run a toy finite-alpha overlap scan.")
    parser.add_argument(
        "--scan-alphas",
        default="0.025,0.016666666666666666,0.0125,0.01,0.0072973525692838015,0.005555555555555556",
        help="Comma-separated alpha values for --finite-alpha-scan.",
    )
    parser.add_argument("--scan-n", type=int, default=15, help="Grid size for --finite-alpha-scan.")
    parser.add_argument("--scan-half-width", type=float, default=4.0, help="Half-width for --finite-alpha-scan.")
    parser.add_argument(
        "--scan-profile",
        choices=("toy", "numerical"),
        default="toy",
        help="Core profile used by --finite-alpha-scan.",
    )
    parser.add_argument("--scan-profile-n", type=int, default=800, help="Vortex profile points for numerical scan profile.")
    parser.add_argument("--scan-profile-x-max", type=float, default=20.0, help="Vortex profile x_max for numerical scan profile.")
    parser.add_argument(
        "--scan-curvature-coeffs",
        default="",
        help="Comma-separated curved-background amplitude coefficients for --finite-alpha-scan.",
    )
    parser.add_argument(
        "--scan-phase-coeffs",
        default="",
        help="Comma-separated curved-background phase coefficients for --finite-alpha-scan.",
    )
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON.")
    return parser.parse_args()


def parse_extra_powers(raw: str) -> list[float]:
    if not raw.strip():
        return []
    return [float(part.strip()) for part in raw.split(",") if part.strip()]


def main() -> None:
    args = parse_args()
    result = run_diagnostic(
        parse_extra_powers(args.extra_factor_powers),
        include_finite_alpha_scan=args.finite_alpha_scan,
        scan_alphas=parse_extra_powers(args.scan_alphas),
        scan_n=args.scan_n,
        scan_half_width=args.scan_half_width,
        curvature_coeffs=tuple(parse_extra_powers(args.scan_curvature_coeffs)),
        phase_coeffs=tuple(parse_extra_powers(args.scan_phase_coeffs)),
        scan_profile=args.scan_profile,
        scan_profile_n=args.scan_profile_n,
        scan_profile_x_max=args.scan_profile_x_max,
    )
    if args.json:
        print(json.dumps(asdict(result), indent=2))
        return

    print("Thin-ring alpha-correction parity diagnostic")
    print(f"leading angular integral int cos^2(theta) dtheta = {result.leading_angular_integral:.12g}")
    print(f"helicity factor                                = {result.helicity_factor:.12g}")
    print(f"BdG symmetrization factor                      = {result.bdg_symmetrization_factor:.12g}")
    print(f"leading bridge factor                          = {result.leading_bridge_factor:.12g}")
    print(f"pi/4                                           = {math.pi / 4.0:.12g}")
    print(f"int cos^3(theta) dtheta                        = {result.integral_cos3:.12g}")
    print(f"verdict                                        = {result.first_order_verdict}")
    print(f"operator verdict                               = {result.operator_verdict}")
    print()
    print("factor_power  c1_per_x        c2_per_x2       name")
    for row in result.factor_corrections:
        print(f"{row.factor_power:12.6g}  {row.c1_per_x: .9e}  {row.c2_per_x2: .9e}  {row.name}")
    print()
    print("operator_projection / leading  raw_projection  name")
    for row in result.operator_terms:
        print(f"{row.normalized_to_leading: .9e}              {row.projection: .9e}  {row.name}")
    if result.finite_alpha_scan is not None:
        print()
        print("finite-alpha baseline current-curl scan")
        print(f"scan interpretation = {result.finite_alpha_scan.interpretation}")
        print(f"chi relative slope  = {result.finite_alpha_scan.chi_relative_slope:.9e}")
        print(f"R relative slope    = {result.finite_alpha_scan.r_relative_slope:.9e}")
        print("alpha          R_e            |chi,K|        rel_chi       |R,K|          rel_R")
        for row in result.finite_alpha_scan.rows:
            print(
                f"{row.alpha: .9e}  {row.ring_radius: .9e}  "
                f"{row.chi_to_kelvin_abs: .9e}  {row.chi_relative_to_first: .9e}  "
                f"{row.r_to_kelvin_abs: .9e}  {row.r_relative_to_first: .9e}"
            )
    if result.curved_background_scan is not None:
        print()
        print("curved-background current-curl scan")
        print(f"scan interpretation = {result.curved_background_scan.interpretation}")
        print(f"chi relative slope  = {result.curved_background_scan.chi_relative_slope:.9e}")
        print(f"R relative slope    = {result.curved_background_scan.r_relative_slope:.9e}")
        print("alpha          R_e            |chi,K|        rel_chi       |R,K|          rel_R")
        for row in result.curved_background_scan.rows:
            print(
                f"{row.alpha: .9e}  {row.ring_radius: .9e}  "
                f"{row.chi_to_kelvin_abs: .9e}  {row.chi_relative_to_first: .9e}  "
                f"{row.r_to_kelvin_abs: .9e}  {row.r_relative_to_first: .9e}"
            )


if __name__ == "__main__":
    main()
