"""#80 Pass 5: can SSV defect labels be assembled into the SO(10) 16?

This is the falsifiable step promised in Pass 4. Pass 4 showed the 16 is the
over-constrained target (one anomaly-free generation) and that 3 of 5 Cartan
charges have SSV homes *conditionally*. Pass 5 makes the assembly DECIDABLE.

The trick: the 16 is generated by five binary coordinates
    (c1, c2, c3, w1, w2) in {+1, -1},  with an EVEN number of -1 signs,
and every SM charge is an explicit linear function of those five bits:

    B - L = (c1 + c2 + c3) / 3                 # Pati-Salam: lepton = 4th colour
    Y     = (c1 + c2 + c3) / 6 - (w1 + w2) / 4
    T3    = (w1 - w2) / 4
    Q_em  = T3 + Y

(all verified below against the standard branching and anomaly cancellation).

So "does an SSV defect carry the 16?" becomes the concrete question: can the
SSV label inventory supply these five bits AND the correlations the 16 imposes
on them? Three correlations are non-trivial and we test each mechanically:

  (i)   multiplicities 6,3,3,2,1,1  -- binomial, automatic once you have 5 bits;
  (ii)  B-L = colour trace          -- B-L is NOT a free label; it is the
        rank-3 (SU(4)) part of colour. SSV's Y-junction (#79) gave only rank-2
        SU(3), so the 4th-colour / B-L bit is an EXTRA the Y-junction lacks;
  (iii) even parity                 -- the 16-vs-32 (chirality) projection
        requires colour-sector parity = weak-sector parity. In SSV the colour
        (Y-junction) and weak (CP^1) sectors are INDEPENDENT topological
        structures, so nothing forces this correlation. This is the obstruction.

RIGOROUS layer = the weight arithmetic (no SSV input). INTERPRETIVE layer =
which SSV labels supply which bits, labelled with honest status.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass
from math import comb


# ===========================================================================
# RIGOROUS LAYER -- the 16 as five binary coordinates + even parity
# ===========================================================================

COORD_NAMES = ("c1", "c2", "c3", "w1", "w2")


def even_parity_weights() -> list[tuple[int, ...]]:
    """The 16: 5-tuples of +/-1 with an even number of -1 (one chirality)."""
    return [s for s in itertools.product((+1, -1), repeat=5) if s.count(-1) % 2 == 0]


def odd_parity_weights() -> list[tuple[int, ...]]:
    """The 16bar (anti-generation): odd number of -1."""
    return [s for s in itertools.product((+1, -1), repeat=5) if s.count(-1) % 2 == 1]


def b_minus_L(w: tuple[int, ...]) -> float:
    c1, c2, c3, _w1, _w2 = w
    return (c1 + c2 + c3) / 3


def hypercharge_Y(w: tuple[int, ...]) -> float:
    c1, c2, c3, w1, w2 = w
    return (c1 + c2 + c3) / 6 - (w1 + w2) / 4


def weak_T3(w: tuple[int, ...]) -> float:
    _c1, _c2, _c3, w1, w2 = w
    return (w1 - w2) / 4


def electric_charge(w: tuple[int, ...]) -> float:
    return weak_T3(w) + hypercharge_Y(w)


def colour_minus(w: tuple[int, ...]) -> int:
    return w[:3].count(-1)


def weak_minus(w: tuple[int, ...]) -> int:
    return w[3:].count(-1)


# field identity is fixed by (colour-minus count, weak-minus count)
FIELD_BY_SECTOR = {
    (0, 0): "nu^c",
    (2, 0): "u^c",
    (0, 2): "e^c",
    (1, 1): "Q",
    (2, 2): "d^c",
    (3, 1): "L",
}


def field_of(w: tuple[int, ...]) -> str:
    return FIELD_BY_SECTOR[(colour_minus(w), weak_minus(w))]


def multiplicity_table() -> dict[str, int]:
    """Count states per field directly from the 16 weights."""
    tally: dict[str, int] = {}
    for w in even_parity_weights():
        tally[field_of(w)] = tally.get(field_of(w), 0) + 1
    return tally


def binomial_multiplicity(nc: int, nw: int) -> int:
    """The multiplicity 6,3,3,2,1,1 is just C(3,nc)*C(2,nw)."""
    return comb(3, nc) * comb(2, nw)


# ===========================================================================
# RIGOROUS LAYER -- correlations the 16 imposes on the five bits
# ===========================================================================

def bL_equals_colour_trace() -> bool:
    """(ii) B-L is exactly the colour trace -> it is the SU(4) 4th-colour U(1),
    not an independent label."""
    return all(
        abs(b_minus_L(w) - (w[0] + w[1] + w[2]) / 3) < 1e-12
        for w in even_parity_weights()
    )


def parity_is_correlated() -> dict[str, bool]:
    """(iii) Even total parity <=> colour-parity == weak-parity.

    colour-parity = c1*c2*c3, weak-parity = w1*w2. Even number of -1 overall
    means (#minus in colour) + (#minus in weak) is even, i.e. the two sectors
    have EQUAL parity. We confirm the 16 enforces this and the 16bar enforces
    the opposite (unequal parity)."""
    sixteen_ok = all(
        (w[0] * w[1] * w[2]) == (w[3] * w[4]) for w in even_parity_weights()
    )
    sixteenbar_ok = all(
        (w[0] * w[1] * w[2]) == -(w[3] * w[4]) for w in odd_parity_weights()
    )
    return {"16 ties colour-parity = weak-parity": sixteen_ok,
            "16bar ties colour-parity = -weak-parity": sixteenbar_ok}


def anomaly_sums() -> dict[str, float]:
    """All gauge + gravitational anomalies over the 16 (each must vanish)."""
    ws = even_parity_weights()
    sum_Y = sum(hypercharge_Y(w) for w in ws)
    sum_Y3 = sum(hypercharge_Y(w) ** 3 for w in ws)
    sum_Q = sum(electric_charge(w) for w in ws)
    # [SU(2)]^2 U(1): doublet members carry T3 = +/-1/4 here; weight by Y over
    # the weak-doublet states (those with nonzero T3).
    su2_u1 = sum(hypercharge_Y(w) for w in ws if abs(weak_T3(w)) > 1e-9)
    # [SU(3)]^2 U(1): sum Y over coloured (nc in {1,2}) states.
    su3_u1 = sum(hypercharge_Y(w) for w in ws if colour_minus(w) in (1, 2))
    return {
        "grav-U(1)  (sum Y)": sum_Y,
        "[U(1)]^3   (sum Y^3)": sum_Y3,
        "[SU(2)]^2 U(1)": su2_u1,
        "[SU(3)]^2 U(1)": su3_u1,
        "sum electric charge": sum_Q,
    }


# ===========================================================================
# INTERPRETIVE LAYER -- which SSV label supplies which of the five bits
# ===========================================================================

@dataclass(frozen=True)
class BitSource:
    bit: str
    ssv_label: str
    status: str          # PRESENT / CONDITIONAL-SPINOR / NEEDS-ENLARGEMENT / NOT-FORCED
    note: str


def ssv_bit_inventory() -> list[BitSource]:
    return [
        BitSource(
            "c1,c2 (colour SU(3) rank-2)",
            "Y-junction phase-balance torus (#79)",
            "PRESENT",
            "the trivalent phase balance gives exactly the SU(3) maximal torus -> "
            "two of the three colour bits (the SU(3) Cartan).",
        ),
        BitSource(
            "c1+c2+c3 (the 3rd colour bit = B-L = 4th colour)",
            "knot/graph type, but it must COMBINE with SU(3) into SU(4)",
            "NEEDS-ENLARGEMENT",
            "B-L is the colour trace (Pati-Salam 'lepton = 4th colour'), not a free "
            "knot label. SSV colour must enlarge from the rank-2 SU(3) of #79 to "
            "rank-3 SU(4); the extra bit is exactly B-L. A loose knot-type U(1) does "
            "NOT automatically sit inside SU(4) with SU(3) -- that is a real demand.",
        ),
        BitSource(
            "w1-w2 (weak isospin T3)",
            "CP^1 internal up-down (#78)",
            "CONDITIONAL-SPINOR",
            "one CP^1 doublet bit supplies T3 = (w1-w2)/4; this is the spinor #78 "
            "needs for spin-1/2. The single S^2 direction gives ONE weak bit.",
        ),
        BitSource(
            "w1+w2 (2nd weak bit -> feeds Y and parity)",
            "winding <-> spinor-framing map",
            "CONDITIONAL-SPINOR",
            "Y = (colour trace)/6 - (w1+w2)/4 needs a SECOND weak bit beyond T3; "
            "it is the framing/winding combination, not yet fixed.",
        ),
        BitSource(
            "even parity (chirality: 16 not 32)",
            "would require Y-junction parity == CP^1 framing parity",
            "NOT-FORCED",
            "THE OBSTRUCTION: the 16 demands colour-sector parity = weak-sector "
            "parity. In SSV the colour (Y-junction) and weak (CP^1) sectors are "
            "INDEPENDENT topological structures, so both parities occur -> SSV "
            "predicts the full 32 (vector-like 16+16bar) unless a mechanism ties "
            "Y-junction parity to CP^1 framing parity. None is present.",
        ),
    ]


# ===========================================================================
# Report
# ===========================================================================

def main() -> None:
    ws = even_parity_weights()

    print("=" * 92)
    print("PASS 5a/5b (RIGOROUS): the 16 as five binary bits + even parity")
    print("=" * 92)
    print(f"  even-parity weights (the 16)  : {len(ws)}")
    print(f"  odd-parity  weights (the 16bar): {len(odd_parity_weights())}")
    print(f"  total 2^5                      : {len(ws) + len(odd_parity_weights())}")
    assert len(ws) == 16

    print("\n  SM identification (charges are explicit functions of the 5 bits):")
    print(f"    {'field':6s} {'nc':>2s} {'nw':>2s} {'mult':>4s} {'binom':>5s} "
          f"{'T3':>6s} {'Y':>7s} {'B-L':>6s} {'Q_em':>6s}")
    seen = set()
    mult = multiplicity_table()
    for w in ws:
        f = field_of(w)
        if f in seen:
            continue
        seen.add(f)
        nc, nw = colour_minus(w), weak_minus(w)
        print(f"    {f:6s} {nc:>2d} {nw:>2d} {mult[f]:>4d} {binomial_multiplicity(nc, nw):>5d} "
              f"{weak_T3(w):>6.2f} {hypercharge_Y(w):>7.3f} {b_minus_L(w):>6.2f} "
              f"{electric_charge(w):>6.2f}")
    print(f"    {'TOTAL':6s} {'':>2s} {'':>2s} {sum(mult.values()):>4d}")
    assert sum(mult.values()) == 16
    assert mult == {"Q": 6, "u^c": 3, "d^c": 3, "L": 2, "e^c": 1, "nu^c": 1}

    print("\n  (i) multiplicities 6,3,3,2,1,1 reproduced by binomial C(3,nc)*C(2,nw): "
          f"{'OK' if all(mult[FIELD_BY_SECTOR[s]] == binomial_multiplicity(*s) for s in FIELD_BY_SECTOR) else 'FAIL'}")

    print("\n  Anomaly coefficients over the 16 (must vanish):")
    for k, v in anomaly_sums().items():
        print(f"    {k:22s} = {v:+.6f}   {'OK' if abs(v) < 1e-12 else 'NONZERO'}")
    assert all(abs(v) < 1e-12 for v in anomaly_sums().values())

    print("\n  (ii) B-L = colour trace (c1+c2+c3)/3 for all 16 weights : "
          f"{'OK -> B-L is the 4th-colour U(1), not a free label' if bL_equals_colour_trace() else 'FAIL'}")
    assert bL_equals_colour_trace()

    print("\n  (iii) parity correlation imposed by the 16 / 16bar:")
    for k, v in parity_is_correlated().items():
        print(f"     {k:42s}: {'OK' if v else 'FAIL'}")
    assert all(parity_is_correlated().values())

    print("\n" + "=" * 92)
    print("PASS 5b (INTERPRETIVE): can SSV labels supply the five bits + parity?")
    print("=" * 92)
    counts: dict[str, int] = {}
    for b in ssv_bit_inventory():
        counts[b.status] = counts.get(b.status, 0) + 1
        print(f"\n  [{b.status}] {b.bit}")
        print(f"      SSV: {b.ssv_label}")
        print(f"      {b.note}")
    print("\n  bit-source tally:", ", ".join(f"{k}={v}" for k, v in counts.items()))

    print("\n" + "=" * 92)
    print("VERDICT")
    print("=" * 92)
    print("""
  DECIDABLE RESULT: the 16's INTERNAL arithmetic is automatic once you possess
  five binary bits -- multiplicities (6,3,3,2,1,1) and anomaly cancellation both
  fall out with no tuning. But assembling those five bits from SSV labels is NOT
  free; two specific correlations the 16 imposes are not supplied by SSV's
  independent topological sectors:

    * B-L is the COLOUR TRACE (Pati-Salam 'lepton = 4th colour'), so colour must
      enlarge from the rank-2 SU(3) of #79 to rank-3 SU(4). A free knot-type U(1)
      does not automatically embed in SU(4) alongside SU(3). [NEEDS-ENLARGEMENT]

    * The chirality projection (16 not 32) demands colour-sector parity =
      weak-sector parity. SSV's colour (Y-junction) and weak (CP^1) sectors are
      INDEPENDENT, so nothing forces this -- SSV as it stands predicts the full,
      vector-like 32. Selecting one chirality needs a mechanism tying Y-junction
      parity to CP^1 framing parity, which does not exist yet. [NOT-FORCED]

  So the honest answer to 'does an SSV defect carry the 16?' is: the bits CAN be
  packed into a 16, but only by IMPOSING (a) colour = SU(4) so B-L is the 4th
  colour, and (b) a colour<->weak parity link to get one chirality. These are not
  derived from the scalar core + #78 spinor + #79 Y-junction; they are two new
  structural demands. The intuition that 'if SSV were right this should be easy'
  is borne out: it is not easy -- the 16 does not drop out, it must be arranged.

  This SHARPENS rather than kills the programme: it converts 'build a CP^1 LogSE'
  into two concrete falsifiable requirements (SU(4) colour with B-L = 4th colour;
  a parity-locking mechanism between the Y-junction and the spinor framing). If a
  minimal multi-component LogSE forces BOTH for free, that is the over-constrained
  hit. If it cannot, the scalar core needs replacing, not patching.
""")


if __name__ == "__main__":
    main()
