"""#79: does the SSV Y-junction phase-balance algebra close to SU(3) colour?

Decides whether the moves admissible on a static trivalent Psi-junction generate
continuous SU(3), or only a smaller structure.

State space (Task 1):
  Three legs, each carrying a U(1) phase theta_i, with the Kirchhoff phase-balance
  constraint theta_1 + theta_2 + theta_3 = 0 (mod 2pi). The balanced space is the
  2-torus T^2 = {(theta_1,theta_2,theta_3) : sum = 0}.

Admissible moves (Task 2):
  - relative-phase rotations preserving the balance constraint  (continuous)
  - leg permutations (R3-type slides)                           (discrete)

Algebra (Task 3) — the central result:
  The maximal torus of SU(3) is exactly
      T = { diag(e^{i phi_1}, e^{i phi_2}, e^{i phi_3}) : phi_1+phi_2+phi_3 = 0 },
  which is identical to the balanced phase space (theta_i = phi_i). The leg
  permutations act on T by permuting (phi_1,phi_2,phi_3) — this is *exactly* the
  Weyl group W(SU(3)) = N(T)/T = S_3.

  So the Y-junction realises the normaliser of the maximal torus,
      N(T) = T  rtimes  S_3,
  with 2 continuous (Cartan) generators + the discrete Weyl group S_3.

  It does NOT realise the 6 off-diagonal su(3) generators (the root vectors
  E_{+/-alpha}, i.e. Gell-Mann lambda_{1,2,4,5,6,7}). Those continuously rotate
  one colour leg into another; on a fixed spatial junction that is physical
  transport/reconnection (the SU(2) weak channel), not an internal colour symmetry.

Verdict: PARTIAL — Cartan torus U(1)^2 + Weyl S_3 of SU(3), not full SU(3).

This module proves the group-theory facts numerically:
  (a) balanced phase space has dimension 2 (= rank SU(3));
  (b) leg permutations realise S_3 = Weyl(SU(3)) acting correctly on the Cartan;
  (c) the Lie algebra generated by the admissible continuous moves is abelian of
      dimension 2 (the Cartan u(1)^2), NOT su(3) (dimension 8);
  (d) exactly the 2 diagonal Gell-Mann generators are realised; the 6 off-diagonal
      ones are not.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass

import numpy as np

# ---------------------------------------------------------------------------
# Gell-Mann basis of su(3)
# ---------------------------------------------------------------------------

def gell_mann() -> list[np.ndarray]:
    """The 8 Gell-Mann matrices (Hermitian generators of su(3))."""
    l1 = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 0]], dtype=complex)
    l2 = np.array([[0, -1j, 0], [1j, 0, 0], [0, 0, 0]], dtype=complex)
    l3 = np.array([[1, 0, 0], [0, -1, 0], [0, 0, 0]], dtype=complex)
    l4 = np.array([[0, 0, 1], [0, 0, 0], [1, 0, 0]], dtype=complex)
    l5 = np.array([[0, 0, -1j], [0, 0, 0], [1j, 0, 0]], dtype=complex)
    l6 = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0]], dtype=complex)
    l7 = np.array([[0, 0, 0], [0, 0, -1j], [0, 1j, 0]], dtype=complex)
    l8 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, -2]], dtype=complex) / np.sqrt(3.0)
    return [l1, l2, l3, l4, l5, l6, l7, l8]


def is_diagonal(M: np.ndarray, tol: float = 1e-12) -> bool:
    return np.allclose(M - np.diag(np.diag(M)), 0.0, atol=tol)


# ---------------------------------------------------------------------------
# Task 1: balanced phase space
# ---------------------------------------------------------------------------

def balanced_phase_space_dimension() -> int:
    """Dimension of {(t1,t2,t3): t1+t2+t3=0}: three phases, one constraint -> 2."""
    # basis of the constraint surface (kernel of [1,1,1])
    constraint = np.array([[1.0, 1.0, 1.0]])
    # nullspace dimension
    _, s, vh = np.linalg.svd(constraint)
    rank = int((s > 1e-12).sum())
    return 3 - rank


# ---------------------------------------------------------------------------
# Task 2 & 3a: continuous moves -> Cartan generators of su(3)
# ---------------------------------------------------------------------------

def cartan_generators_from_balanced_phases() -> list[np.ndarray]:
    """Continuous relative-phase rotations on the balanced torus.

    A phase rotation acts as U = diag(e^{i a1}, e^{i a2}, e^{i a3}); preserving the
    balance constraint sum(theta)=0 requires the *generator* to be traceless
    diagonal, i.e. a1+a2+a3 = 0. The space of such Hermitian generators is exactly
    the Cartan subalgebra of su(3): span{lambda_3, lambda_8}.
    """
    diag1 = np.diag([1.0, -1.0, 0.0]).astype(complex)            # ~ lambda_3
    diag2 = np.diag([1.0, 1.0, -2.0]).astype(complex) / np.sqrt(3.0)  # ~ lambda_8
    return [diag1, diag2]


def lie_closure(generators: list[np.ndarray], tol: float = 1e-9, max_iter: int = 50) -> int:
    """Dimension of the Lie algebra generated by `generators` (over iR, Hermitian).

    Repeatedly adjoins commutators i[A,B] (kept Hermitian) until the real span
    stops growing; returns its dimension.
    """
    def flat(mats):
        return np.array([m.flatten() for m in mats])

    def real_rank(mats):
        # treat complex matrices as real vectors (re, im stacked)
        V = flat(mats)
        Vr = np.hstack([V.real, V.imag])
        if Vr.shape[0] == 0:
            return 0
        s = np.linalg.svd(Vr, compute_uv=False)
        return int((s > tol).sum())

    basis = list(generators)
    dim = real_rank(basis)
    for _ in range(max_iter):
        new = list(basis)
        for A, B in itertools.combinations(basis, 2):
            C = 1j * (A @ B - B @ A)   # i[A,B] is Hermitian if A,B are
            new.append(C)
        d_new = real_rank(new)
        if d_new == dim:
            break
        # rebuild an independent basis to keep matrices small
        basis = new
        dim = d_new
    return dim


# ---------------------------------------------------------------------------
# Task 2 & 3b: leg permutations -> Weyl group S_3
# ---------------------------------------------------------------------------

def permutation_matrices() -> list[np.ndarray]:
    """The 6 leg-permutation matrices acting on the three colour legs (= S_3)."""
    mats = []
    for perm in itertools.permutations(range(3)):
        P = np.zeros((3, 3))
        for i, j in enumerate(perm):
            P[i, j] = 1.0
        mats.append(P)
    return mats


def permutations_form_s3() -> bool:
    """Verify the 6 permutation matrices close under multiplication (group S_3)."""
    mats = permutation_matrices()
    keys = {M.tobytes() for M in mats}
    for A in mats:
        for B in mats:
            if (A @ B).tobytes() not in keys:
                return False
    return len(mats) == 6


def permutations_act_as_weyl_on_cartan() -> bool:
    """A leg permutation P conjugates a Cartan element diag(t) into diag(P t),
    i.e. it permutes the torus coordinates — the defining Weyl action."""
    P = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]], dtype=float)  # swap legs 1,2
    t = np.array([0.3, -0.5, 0.2])
    D = np.diag(t).astype(complex)
    conj = P @ D @ P.T
    expected = np.diag(t[[1, 0, 2]]).astype(complex)
    return np.allclose(conj, expected)


# ---------------------------------------------------------------------------
# Task 3c/d & verdict
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SU3Verdict:
    balanced_dim: int
    su3_dim: int
    cartan_dim: int
    generated_algebra_dim: int
    realised_gellmann_diagonal: int
    missing_gellmann_offdiagonal: int
    permutations_are_s3: bool
    weyl_action_ok: bool
    verdict: str


def analyse() -> SU3Verdict:
    gm = gell_mann()
    diag_count = sum(1 for L in gm if is_diagonal(L))
    offdiag_count = sum(1 for L in gm if not is_diagonal(L))

    cartan = cartan_generators_from_balanced_phases()
    gen_dim = lie_closure(cartan)

    bdim = balanced_phase_space_dimension()
    su3_dim = len(gm)  # 8

    s3 = permutations_form_s3()
    weyl = permutations_act_as_weyl_on_cartan()

    # Decision rule (pre-registered in issue #79)
    if gen_dim == su3_dim:
        verdict = "SU(3) PASS"
    elif gen_dim == 2 and s3 and weyl:
        verdict = "PARTIAL (maximal torus U(1)^2 + Weyl S_3 of SU(3); off-diagonal generators absent)"
    elif gen_dim == 0:
        verdict = "DISCRETE-ONLY (S_3/C_3 permutation symmetry, no continuous colour generators)"
    else:
        verdict = f"OTHER (generated algebra dim {gen_dim})"

    return SU3Verdict(
        balanced_dim=bdim,
        su3_dim=su3_dim,
        cartan_dim=len(cartan),
        generated_algebra_dim=gen_dim,
        realised_gellmann_diagonal=diag_count,
        missing_gellmann_offdiagonal=offdiag_count,
        permutations_are_s3=s3,
        weyl_action_ok=weyl,
        verdict=verdict,
    )


def main() -> None:
    v = analyse()
    print("#79: SSV Y-junction phase-balance -> SU(3)?  Group-theory analysis\n")
    print(f"  balanced phase space dim          : {v.balanced_dim}  (= rank SU(3) = 2)")
    print(f"  su(3) dimension                   : {v.su3_dim}")
    print(f"  continuous moves generate algebra : dim {v.generated_algebra_dim}  (abelian Cartan u(1)^2)")
    print(f"  Gell-Mann diagonal realised       : {v.realised_gellmann_diagonal}  (lambda_3, lambda_8)")
    print(f"  Gell-Mann off-diagonal missing    : {v.missing_gellmann_offdiagonal}  (lambda_1,2,4,5,6,7)")
    print(f"  leg permutations form S_3         : {v.permutations_are_s3}")
    print(f"  permutations act as Weyl group    : {v.weyl_action_ok}")
    print(f"\n  VERDICT: {v.verdict}")


if __name__ == "__main__":
    main()
