"""Generate the "Code and Issue References" provenance appendix for SSV papers.

Every paper cites GitHub issues (`\\#NN`) and Python scripts (`\\texttt{src/...}`).
This tool makes each reference *checkable*: it scans a paper's `main.tex`, resolves
each issue to its GitHub URL and each script to a permalink pinned at the commit
that last modified it, and writes `papers/<PAPER>/provenance.tex` for the paper to
`\\input` inside an appendix.

Design (decided 2026-06-07):
  * per-script permalink, pinned to the commit that last modified the file;
  * auto-generated (regenerate before a build/release — it cannot drift);
  * rendered as an appendix section.

Usage:
    python src/tools/gen_provenance.py SSV-I        # one paper
    python src/tools/gen_provenance.py --all        # every papers/SSV-*/main.tex
    python src/tools/gen_provenance.py --all --check # report broken refs, write nothing
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PAPERS = REPO_ROOT / "papers"

ISSUE_RE = re.compile(r"\\#(\d+)")
TEXTTT_RE = re.compile(r"\\texttt\{([^{}]*)\}", re.DOTALL)


# --------------------------------------------------------------------------
# Git helpers
# --------------------------------------------------------------------------

def _git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        capture_output=True, text=True, check=True,
    ).stdout.strip()


def repo_slug() -> str:
    """e.g. 'StigNorland/SVT' from the origin remote URL."""
    url = _git("remote", "get-url", "origin")
    m = re.search(r"github\.com[:/](.+?)(?:\.git)?$", url)
    return m.group(1) if m else "StigNorland/SVT"


def head_commit() -> str:
    return _git("rev-parse", "--short", "HEAD")


def last_commit(path: str) -> str | None:
    """Short SHA of the commit that last modified `path`, or None if untracked."""
    sha = _git("log", "-1", "--format=%h", "--", path)
    return sha or None


# --------------------------------------------------------------------------
# Reference extraction
# --------------------------------------------------------------------------

def _normalise_path(raw: str) -> str:
    """Strip LaTeX whitespace/line-wraps and unescape `\\_` etc. in a path."""
    p = re.sub(r"\s+", "", raw)                 # paths contain no spaces; join wraps
    return p.replace("\\_", "_").replace("\\#", "#").replace("\\%", "%").replace("\\&", "&")


def extract_refs(tex: str) -> tuple[list[int], list[str]]:
    """Return (sorted unique issue numbers, sorted unique src/*.py paths) cited."""
    issues = sorted({int(n) for n in ISSUE_RE.findall(tex)})
    paths = set()
    for raw in TEXTTT_RE.findall(tex):
        p = _normalise_path(raw)
        if p.startswith("src/") and p.endswith(".py"):
            paths.add(p)
    return issues, sorted(paths)


def missing_code_paths(paths: list[str]) -> list[str]:
    """Cited script paths that do not exist as tracked files in the repo."""
    return [p for p in paths if not (REPO_ROOT / p).is_file()]


def unresolved_issues(issues: list[int], slug: str) -> list[int]:
    """Issue numbers that do not resolve on GitHub (needs network + gh CLI).

    Used only by --verify-issues; offline runs skip this."""
    bad = []
    for n in issues:
        r = subprocess.run(["gh", "api", f"repos/{slug}/issues/{n}", "--jq", ".number"],
                           capture_output=True, text=True)
        if r.returncode != 0 or not r.stdout.strip():
            bad.append(n)
    return bad


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

def _tex_path(path: str) -> str:
    """LaTeX-safe rendering of a path inside \\texttt (escape underscores)."""
    return path.replace("_", r"\_")


def render(paper: str, issues: list[int], paths: list[str], slug: str, head: str) -> str:
    base = f"https://github.com/{slug}"
    lines = [
        f"% Auto-generated by src/tools/gen_provenance.py — do not edit by hand.",
        f"% Regenerate: python src/tools/gen_provenance.py {paper}",
        r"\providecommand{\url}[1]{\texttt{#1}}% graceful fallback if hyperref absent",
        r"\section{Code and Issue References}",
        r"\label{app:provenance}",
        f"Prepared against repository commit \\texttt{{{head}}} "
        f"(\\url{{{base}}}).  Each reference below is pinned so it can be checked "
        r"directly: issues link to their tracker entry, and each script links to the"
        r" exact version (the commit that last modified it).",
        "",
    ]

    if issues:
        lines += [r"\paragraph{Issues.}", r"\begin{itemize}\setlength\itemsep{1pt}"]
        for n in issues:
            lines.append(f"  \\item \\#{n} --- \\url{{{base}/issues/{n}}}")
        lines += [r"\end{itemize}", ""]

    if paths:
        lines += [
            r"\paragraph{Code (each pinned to the commit that last modified it).}",
            r"\begin{itemize}\setlength\itemsep{2pt}",
        ]
        for p in paths:
            sha = last_commit(p)
            if sha:
                lines.append(
                    f"  \\item \\texttt{{{_tex_path(p)}}} @\\,\\texttt{{{sha}}} ---\\\\"
                )
                lines.append(f"        {{\\small\\url{{{base}/blob/{sha}/{p}}}}}")
            else:
                lines.append(
                    f"  \\item \\texttt{{{_tex_path(p)}}} --- "
                    r"\textbf{[untracked --- not found in the repository]}"
                )
        lines += [r"\end{itemize}", ""]

    if not issues and not paths:
        lines.append("This paper makes no external code or issue references.")
        lines.append("")

    return "\n".join(lines)


# --------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------

def generate(paper: str, slug: str, head: str, check: bool) -> dict:
    main_tex = PAPERS / paper / "main.tex"
    if not main_tex.is_file():
        raise FileNotFoundError(main_tex)
    issues, paths = extract_refs(main_tex.read_text(encoding="utf-8"))
    missing = missing_code_paths(paths)
    if not check:
        (PAPERS / paper / "provenance.tex").write_text(
            render(paper, issues, paths, slug, head), encoding="utf-8"
        )
    return {"paper": paper, "issues": issues, "paths": paths, "missing": missing}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("paper", nargs="?", help="paper dir name, e.g. SSV-I")
    ap.add_argument("--all", action="store_true", help="all papers/SSV-*/main.tex")
    ap.add_argument("--check", action="store_true",
                    help="report broken refs, write nothing (exit 1 if any missing)")
    ap.add_argument("--verify-issues", action="store_true",
                    help="also check each issue resolves on GitHub (needs gh + network)")
    args = ap.parse_args()

    if args.all:
        papers = sorted(p.parent.name for p in PAPERS.glob("SSV-*/main.tex"))
    elif args.paper:
        papers = [args.paper]
    else:
        ap.error("give a paper name or --all")

    slug, head = repo_slug(), head_commit()
    any_problem = False
    for paper in papers:
        r = generate(paper, slug, head, args.check)
        bad_issues = unresolved_issues(r["issues"], slug) if args.verify_issues else []
        tag = "CHECK" if args.check else "wrote"
        msg = f"{tag} {paper}: {len(r['issues'])} issues, {len(r['paths'])} scripts"
        if r["missing"]:
            msg += f"  ⚠ MISSING scripts: {r['missing']}"
        if bad_issues:
            msg += f"  ⚠ UNRESOLVED issues: {bad_issues}"
        print(msg)
        any_problem |= bool(r["missing"]) or bool(bad_issues)
    if any_problem:
        print("\nERROR: some references are not checkable — fix them.")
        sys.exit(1)


if __name__ == "__main__":
    main()
